// pages/projekte/lernzettel/js/interactive_questions.js
// 30 Fragen pro Fach — i18n-fähig (Keys werden über i18n.t() aufgelöst)
// Jede Frage ist ein i18n-Key: 'lz.q.{fachId}.{index}'

/**
 * Gibt die i18n-Keys für alle Fragen eines Fachs zurück.
 * Die tatsächlichen Texte liegen in den Sprachdateien.
 */
export function getQuestionKeys(fachId, count = 30) {
  return Array.from({ length: count }, (_, i) => `lz.q.${fachId}.${i}`);
}

// ══════════════════════════════════════════════════════════
// DEUTSCH — Fragen-Übersetzungen
// ══════════════════════════════════════════════════════════

export const questionsDE = {
  // ── Chemie ──
  'lz.q.chemie.0':  'Was beschreibt das Bohrsche Atommodell?',
  'lz.q.chemie.1':  'Wie unterscheiden sich σ- und π-Bindungen?',
  'lz.q.chemie.2':  'Was ist eine exotherme Reaktion?',
  'lz.q.chemie.3':  'Welche Funktion hat ein Katalysator?',
  'lz.q.chemie.4':  'Was besagt das Prinzip von Le Chatelier?',
  'lz.q.chemie.5':  'Was ist der Unterschied zwischen Oxidation und Reduktion?',
  'lz.q.chemie.6':  'Wie ist das Periodensystem aufgebaut?',
  'lz.q.chemie.7':  'Was sind Van-der-Waals-Kräfte?',
  'lz.q.chemie.8':  'Was ist eine galvanische Zelle?',
  'lz.q.chemie.9':  'Wie berechnet man den pH-Wert?',
  'lz.q.chemie.10': 'Was ist eine Säure nach Brønsted?',
  'lz.q.chemie.11': 'Was versteht man unter Hybridisierung?',
  'lz.q.chemie.12': 'Wie funktioniert eine Elektrolyse?',
  'lz.q.chemie.13': 'Was ist ein Mol?',
  'lz.q.chemie.14': 'Wozu dient eine Titration?',
  'lz.q.chemie.15': 'Was sind funktionelle Gruppen?',
  'lz.q.chemie.16': 'Wie lautet die allgemeine Gasgleichung?',
  'lz.q.chemie.17': 'Was ist der Unterschied zwischen Isomerie-Arten?',
  'lz.q.chemie.18': 'Was beschreibt die Enthalpie?',
  'lz.q.chemie.19': 'Was ist eine Pufferlösung?',
  'lz.q.chemie.20': 'Wie funktioniert ein Indikator?',
  'lz.q.chemie.21': 'Was ist die Oktettregel?',
  'lz.q.chemie.22': 'Welche Bindungsarten gibt es?',
  'lz.q.chemie.23': 'Was sind Alkohole, Aldehyde, Ketone?',
  'lz.q.chemie.24': 'Was passiert bei der Veresterung?',
  'lz.q.chemie.25': 'Was ist eine Redoxreaktion?',
  'lz.q.chemie.26': 'Wie wirkt sich die Elektronegativität aus?',
  'lz.q.chemie.27': 'Was ist ein Dipol?',
  'lz.q.chemie.28': 'Wie entsteht eine Wasserstoffbrücke?',
  'lz.q.chemie.29': 'Was ist der Unterschied zwischen Atom und Ion?',

  // ── Deutsch ──
  'lz.q.deutsch.0':  'Was sind die vier Seiten einer Nachricht?',
  'lz.q.deutsch.1':  'Wie analysiert man eine Kurzgeschichte?',
  'lz.q.deutsch.2':  'Was ist der Unterschied zwischen Epik und Dramatik?',
  'lz.q.deutsch.3':  'Welche Merkmale hat die Romantik?',
  'lz.q.deutsch.4':  'Was ist ein lyrisches Ich?',
  'lz.q.deutsch.5':  'Wie baut man eine lineare Erörterung auf?',
  'lz.q.deutsch.6':  'Was ist Kommunikation nach Watzlawick?',
  'lz.q.deutsch.7':  'Welche Erzählperspektiven gibt es?',
  'lz.q.deutsch.8':  'Was kennzeichnet den Expressionismus?',
  'lz.q.deutsch.9':  'Wie schreibt man einen Interpretationsaufsatz?',
  'lz.q.deutsch.10': 'Was ist ein Sprachbild?',
  'lz.q.deutsch.11': 'Wozu dient ein Konjunktiv II?',
  'lz.q.deutsch.12': 'Was ist Sturm und Drang?',
  'lz.q.deutsch.13': 'Wie analysiert man Sachtexte?',
  'lz.q.deutsch.14': 'Was ist eine textgebundene Erörterung?',
  'lz.q.deutsch.15': 'Welche Rolle spielt der Erzähler?',
  'lz.q.deutsch.16': 'Was versteht man unter Epochenumbruch?',
  'lz.q.deutsch.17': 'Wie funktioniert eine Dramenanalyse?',
  'lz.q.deutsch.18': 'Was sind rhetorische Mittel?',
  'lz.q.deutsch.19': 'Was ist der Unterschied zwischen Fabel und Parabel?',
  'lz.q.deutsch.20': 'Wie analysiert man Gedichte formell?',
  'lz.q.deutsch.21': 'Was bedeutet Intertextualität?',
  'lz.q.deutsch.22': 'Was ist die Weimarer Klassik?',
  'lz.q.deutsch.23': 'Wie schreibt man eine Charakterisierung?',
  'lz.q.deutsch.24': 'Was ist ein innerer Monolog?',
  'lz.q.deutsch.25': 'Welche Satzarten gibt es?',
  'lz.q.deutsch.26': 'Was kennzeichnet die Aufklärung?',
  'lz.q.deutsch.27': 'Was ist eine Novelle?',
  'lz.q.deutsch.28': 'Wie argumentiert man schlüssig?',
  'lz.q.deutsch.29': 'Was ist ein Leitmotiv?',

  // ── Englisch ──
  'lz.q.englisch.0':  'What is the difference between "since" and "for"?',
  'lz.q.englisch.1':  'How do you form the passive voice?',
  'lz.q.englisch.2':  'What is a conditional sentence type III?',
  'lz.q.englisch.3':  'How do you write a summary?',
  'lz.q.englisch.4':  'What is the American Dream?',
  'lz.q.englisch.5':  'When do you use the present perfect?',
  'lz.q.englisch.6':  'What are collocations?',
  'lz.q.englisch.7':  'How do you analyse a political speech?',
  'lz.q.englisch.8':  'What is indirect speech?',
  'lz.q.englisch.9':  'What does "globalisation" mean?',
  'lz.q.englisch.10': 'How do you write a comment?',
  'lz.q.englisch.11': 'What are linking words?',
  'lz.q.englisch.12': 'British vs. American English?',
  'lz.q.englisch.13': 'How do you mediate a text?',
  'lz.q.englisch.14': 'What is a dystopia?',
  'lz.q.englisch.15': 'What are modal verbs used for?',
  'lz.q.englisch.16': 'How do you interpret a cartoon?',
  'lz.q.englisch.17': 'What is the UK political system?',
  'lz.q.englisch.18': 'How do you write a letter to the editor?',
  'lz.q.englisch.19': 'What is multiculturalism?',
  'lz.q.englisch.20': 'Gerund vs. infinitive?',
  'lz.q.englisch.21': 'Protagonist vs. antagonist?',
  'lz.q.englisch.22': 'How do you describe a diagram?',
  'lz.q.englisch.23': 'What is cultural identity?',
  'lz.q.englisch.24': 'What are phrasal verbs?',
  'lz.q.englisch.25': 'How do you write a blog entry?',
  'lz.q.englisch.26': 'What is the Commonwealth?',
  'lz.q.englisch.27': 'What does "sustainability" mean?',
  'lz.q.englisch.28': 'How do you use relative clauses?',
  'lz.q.englisch.29': 'Difference between "make" and "do"?',

  // ── Ethik ──
  'lz.q.ethik.0':  'Was ist der kategorische Imperativ?',
  'lz.q.ethik.1':  'Was unterscheidet Moral von Ethik?',
  'lz.q.ethik.2':  'Was ist Utilitarismus?',
  'lz.q.ethik.3':  'Was bedeutet Menschenwürde?',
  'lz.q.ethik.4':  'Was ist Tugendethik nach Aristoteles?',
  'lz.q.ethik.5':  'Was versteht man unter Gerechtigkeit?',
  'lz.q.ethik.6':  'Was ist das Trolley-Problem?',
  'lz.q.ethik.7':  'Was sagt der Kontraktualismus?',
  'lz.q.ethik.8':  'Was ist Willensfreiheit?',
  'lz.q.ethik.9':  'Was bedeutet Verantwortung nach Jonas?',
  'lz.q.ethik.10': 'Was ist der Naturzustand nach Hobbes?',
  'lz.q.ethik.11': 'Wie steht es um die Sterbehilfe-Debatte?',
  'lz.q.ethik.12': 'Was ist ein ethisches Dilemma?',
  'lz.q.ethik.13': 'Wie funktioniert Kants Pflichtethik?',
  'lz.q.ethik.14': 'Was sind Menschenrechte?',
  'lz.q.ethik.15': 'Was ist Gewissen?',
  'lz.q.ethik.16': 'Handlungs- vs. Regelutilitarismus?',
  'lz.q.ethik.17': 'Was ist ethischer Relativismus?',
  'lz.q.ethik.18': 'Was bedeutet Autonomie?',
  'lz.q.ethik.19': 'Was ist die Goldene Regel?',
  'lz.q.ethik.20': 'Rawls\' Schleier des Nichtwissens?',
  'lz.q.ethik.21': 'Was ist Bioethik?',
  'lz.q.ethik.22': 'Nachhaltigkeit aus ethischer Sicht?',
  'lz.q.ethik.23': 'Was ist Diskursethik?',
  'lz.q.ethik.24': 'Was versteht man unter Toleranz?',
  'lz.q.ethik.25': 'Unterschied zwischen Recht und Moral?',
  'lz.q.ethik.26': 'Was ist Tierethik?',
  'lz.q.ethik.27': 'Was bedeutet Solidarität?',
  'lz.q.ethik.28': 'Ethische Dilemmata der KI?',
  'lz.q.ethik.29': 'Was ist Freiheit nach Kant?',

  // ── Geschichte ──
  'lz.q.geschichte.0':  'Was war die Industrialisierung?',
  'lz.q.geschichte.1':  'Was ist die Weimarer Verfassung?',
  'lz.q.geschichte.2':  'Wie kam Hitler an die Macht?',
  'lz.q.geschichte.3':  'Was war die Reichsgründung 1871?',
  'lz.q.geschichte.4':  'Was ist Gewaltenteilung?',
  'lz.q.geschichte.5':  'Was war der Kalte Krieg?',
  'lz.q.geschichte.6':  'Demokratie vs. Diktatur?',
  'lz.q.geschichte.7':  'Was war der Versailler Vertrag?',
  'lz.q.geschichte.8':  'Was bedeutet Föderalismus?',
  'lz.q.geschichte.9':  'Was war die Deutsche Teilung?',
  'lz.q.geschichte.10': 'Was ist der Sozialstaat?',
  'lz.q.geschichte.11': 'Was war die Revolution 1848?',
  'lz.q.geschichte.12': 'Was ist die NATO?',
  'lz.q.geschichte.13': 'Was war die Entnazifizierung?',
  'lz.q.geschichte.14': 'Was ist die Europäische Integration?',
  'lz.q.geschichte.15': 'Was war die Weltwirtschaftskrise 1929?',
  'lz.q.geschichte.16': 'Was ist das Grundgesetz?',
  'lz.q.geschichte.17': 'Was war die Novemberrevolution 1918?',
  'lz.q.geschichte.18': 'Was bedeutet Imperialismus?',
  'lz.q.geschichte.19': 'Was war der Mauerfall 1989?',
  'lz.q.geschichte.20': 'Was ist eine Verfassung?',
  'lz.q.geschichte.21': 'Was war der Marshall-Plan?',
  'lz.q.geschichte.22': 'Was ist Nationalismus?',
  'lz.q.geschichte.23': 'Was war die Gleichschaltung?',
  'lz.q.geschichte.24': 'Was bedeutet Souveränität?',
  'lz.q.geschichte.25': 'Was war die Ostpolitik Brandts?',
  'lz.q.geschichte.26': 'Wie funktioniert das Wahlsystem der BRD?',
  'lz.q.geschichte.27': 'Was war die Blockbildung?',
  'lz.q.geschichte.28': 'Was bedeutet Parlamentarismus?',
  'lz.q.geschichte.29': 'Was war die Stunde Null?',

  // ── Informatik ──
  'lz.q.informatik.0':  'Unterschied zwischen TCP und UDP?',
  'lz.q.informatik.1':  'Wie funktioniert ein Binärbaum?',
  'lz.q.informatik.2':  'Was ist eine Datenbank-Normalform?',
  'lz.q.informatik.3':  'Was ist das OSI-Modell?',
  'lz.q.informatik.4':  'Wie funktioniert eine SQL-Abfrage?',
  'lz.q.informatik.5':  'Was ist OOP?',
  'lz.q.informatik.6':  'Was ist eine IP-Adresse?',
  'lz.q.informatik.7':  'Wie funktioniert Verschlüsselung?',
  'lz.q.informatik.8':  'Was ist ein Algorithmus?',
  'lz.q.informatik.9':  'Stack vs. Queue?',
  'lz.q.informatik.10': 'Was ist ein Netzwerkprotokoll?',
  'lz.q.informatik.11': 'Wie funktioniert DNS?',
  'lz.q.informatik.12': 'Was ist Rekursion?',
  'lz.q.informatik.13': 'Was ist ein VLAN?',
  'lz.q.informatik.14': 'Was ist ein Array?',
  'lz.q.informatik.15': 'Wie funktioniert HTTP/HTTPS?',
  'lz.q.informatik.16': 'Was ist ein ER-Diagramm?',
  'lz.q.informatik.17': 'Was ist Big-O-Notation?',
  'lz.q.informatik.18': 'Was ist eine Firewall?',
  'lz.q.informatik.19': 'Was sind Zugriffsrechte?',
  'lz.q.informatik.20': 'Was ist ein Subnetz?',
  'lz.q.informatik.21': 'Wie funktioniert eine for-Schleife?',
  'lz.q.informatik.22': 'Was ist eine API?',
  'lz.q.informatik.23': 'Was ist ein Primary Key?',
  'lz.q.informatik.24': 'Client-Server-Architektur?',
  'lz.q.informatik.25': 'Compiler vs. Interpreter?',
  'lz.q.informatik.26': 'Was ist Phishing?',
  'lz.q.informatik.27': 'Was ist eine Variable?',
  'lz.q.informatik.28': 'Was ist Routing?',
  'lz.q.informatik.29': 'Was ist eine Klasse in Java?',

  // ── Spanisch ──
  'lz.q.spanisch.0':  '¿Diferencia entre ser y estar?',
  'lz.q.spanisch.1':  '¿Cómo se forma el subjuntivo?',
  'lz.q.spanisch.2':  '¿Qué es el pretérito indefinido?',
  'lz.q.spanisch.3':  '¿Cómo se usa "por" y "para"?',
  'lz.q.spanisch.4':  '¿Qué son los pronombres relativos?',
  'lz.q.spanisch.5':  '¿Cómo se forma el condicional?',
  'lz.q.spanisch.6':  '¿Qué es un texto argumentativo?',
  'lz.q.spanisch.7':  '¿Cuáles son los tiempos del pasado?',
  'lz.q.spanisch.8':  '¿Qué es el gerundio en español?',
  'lz.q.spanisch.9':  '¿Pronombres de OD y OI?',
  'lz.q.spanisch.10': '¿Voz pasiva en español?',
  'lz.q.spanisch.11': '¿Cuáles son los conectores textuales?',
  'lz.q.spanisch.12': '¿Cómo se forma el imperativo?',
  'lz.q.spanisch.13': '¿Qué es un resumen?',
  'lz.q.spanisch.14': '¿Diferencias España/Latinoamérica?',
  'lz.q.spanisch.15': '¿Qué es el futuro simple?',
  'lz.q.spanisch.16': '¿Cómo se analiza un texto literario?',
  'lz.q.spanisch.17': '¿Qué son los verbos reflexivos?',
  'lz.q.spanisch.18': '¿Cómo se expresan deseos?',
  'lz.q.spanisch.19': '¿Qué es el pluscuamperfecto?',
  'lz.q.spanisch.20': '¿Adverbios de frecuencia?',
  'lz.q.spanisch.21': '¿"Aunque" con indicativo y subjuntivo?',
  'lz.q.spanisch.22': '¿Temas sociales relevantes?',
  'lz.q.spanisch.23': '¿Cómo se describe una imagen?',
  'lz.q.spanisch.24': '¿Inmigración en España?',
  'lz.q.spanisch.25': '¿Oración condicional?',
  'lz.q.spanisch.26': '¿Qué es el estilo indirecto?',
  'lz.q.spanisch.27': '¿Cuáles son los falsos amigos?',
  'lz.q.spanisch.28': '¿Cómo se escribe una carta formal?',
  'lz.q.spanisch.29': '¿Qué es el pretérito imperfecto?',

  // ── Sport ──
  'lz.q.sport.0':  'Was ist das Superkompensationsprinzip?',
  'lz.q.sport.1':  'Welche Ausdauerarten gibt es?',
  'lz.q.sport.2':  'Was ist die maximale Herzfrequenz?',
  'lz.q.sport.3':  'Wie funktioniert Muskelkontraktion?',
  'lz.q.sport.4':  'Kraft vs. Schnelligkeit?',
  'lz.q.sport.5':  'Was ist Koordination?',
  'lz.q.sport.6':  'Welche Energiebereitstellungswege gibt es?',
  'lz.q.sport.7':  'Was ist die Trainingspyramide?',
  'lz.q.sport.8':  'Was versteht man unter Bewegungslernen?',
  'lz.q.sport.9':  'Belastungs-Erholungs-Modell?',
  'lz.q.sport.10': 'Was sind motorische Grundeigenschaften?',
  'lz.q.sport.11': 'Was ist Periodisierung?',
  'lz.q.sport.12': 'Wie funktioniert aerober Stoffwechsel?',
  'lz.q.sport.13': 'Was ist Flexibilität?',
  'lz.q.sport.14': 'Dehnen vs. Mobilisieren?',
  'lz.q.sport.15': 'Prinzip der progressiven Belastung?',
  'lz.q.sport.16': 'Welche Gelenkstypen gibt es?',
  'lz.q.sport.17': 'Was ist Laktat?',
  'lz.q.sport.18': 'Was sind sportmotorische Tests?',
  'lz.q.sport.19': 'Was ist mentales Training?',
  'lz.q.sport.20': 'Ernährung und Leistung?',
  'lz.q.sport.21': 'Was ist Propriozeption?',
  'lz.q.sport.22': 'Prinzipien der Trainingslehre?',
  'lz.q.sport.23': 'Was ist Regeneration?',
  'lz.q.sport.24': 'Wie wirkt Doping?',
  'lz.q.sport.25': 'Was ist der BMI?',
  'lz.q.sport.26': 'Was ist funktionelles Training?',
  'lz.q.sport.27': 'Welche Muskelfasertypen gibt es?',
  'lz.q.sport.28': 'Was ist die anaerobe Schwelle?',
  'lz.q.sport.29': 'Was bedeutet Fair Play?',
};

// ══════════════════════════════════════════════════════════
// ENGLISCH
// ══════════════════════════════════════════════════════════

export const questionsEN = {
  'lz.q.chemie.0': 'What does the Bohr atomic model describe?', 'lz.q.chemie.1': 'How do σ and π bonds differ?', 'lz.q.chemie.2': 'What is an exothermic reaction?', 'lz.q.chemie.3': 'What is the function of a catalyst?', 'lz.q.chemie.4': 'What does Le Chatelier\'s principle state?', 'lz.q.chemie.5': 'Oxidation vs. reduction?', 'lz.q.chemie.6': 'How is the periodic table structured?', 'lz.q.chemie.7': 'What are Van der Waals forces?', 'lz.q.chemie.8': 'What is a galvanic cell?', 'lz.q.chemie.9': 'How do you calculate pH?', 'lz.q.chemie.10': 'What is a Brønsted acid?', 'lz.q.chemie.11': 'What is hybridization?', 'lz.q.chemie.12': 'How does electrolysis work?', 'lz.q.chemie.13': 'What is a mole?', 'lz.q.chemie.14': 'What is titration used for?', 'lz.q.chemie.15': 'What are functional groups?', 'lz.q.chemie.16': 'What is the ideal gas law?', 'lz.q.chemie.17': 'Types of isomerism?', 'lz.q.chemie.18': 'What does enthalpy describe?', 'lz.q.chemie.19': 'What is a buffer solution?', 'lz.q.chemie.20': 'How does an indicator work?', 'lz.q.chemie.21': 'What is the octet rule?', 'lz.q.chemie.22': 'What types of bonds exist?', 'lz.q.chemie.23': 'Alcohols, aldehydes, ketones?', 'lz.q.chemie.24': 'What happens during esterification?', 'lz.q.chemie.25': 'What is a redox reaction?', 'lz.q.chemie.26': 'How does electronegativity affect bonds?', 'lz.q.chemie.27': 'What is a dipole?', 'lz.q.chemie.28': 'How do hydrogen bonds form?', 'lz.q.chemie.29': 'Atom vs. ion?',
  'lz.q.deutsch.0': 'What are the four sides of a message?', 'lz.q.deutsch.1': 'How do you analyse a short story?', 'lz.q.deutsch.2': 'Epic vs. dramatic literature?', 'lz.q.deutsch.3': 'Features of Romanticism?', 'lz.q.deutsch.4': 'What is the lyrical self?', 'lz.q.deutsch.5': 'How to structure a linear essay?', 'lz.q.deutsch.6': 'Watzlawick\'s communication theory?', 'lz.q.deutsch.7': 'What narrative perspectives exist?', 'lz.q.deutsch.8': 'Features of Expressionism?', 'lz.q.deutsch.9': 'How to write an interpretation essay?', 'lz.q.deutsch.10': 'What is a figure of speech?', 'lz.q.deutsch.11': 'What is the subjunctive II for?', 'lz.q.deutsch.12': 'What is Sturm und Drang?', 'lz.q.deutsch.13': 'How to analyse non-fiction texts?', 'lz.q.deutsch.14': 'What is a text-based essay?', 'lz.q.deutsch.15': 'Role of the narrator?', 'lz.q.deutsch.16': 'What is an epoch transition?', 'lz.q.deutsch.17': 'How to analyse a drama?', 'lz.q.deutsch.18': 'What are rhetorical devices?', 'lz.q.deutsch.19': 'Fable vs. parable?', 'lz.q.deutsch.20': 'How to analyse a poem formally?', 'lz.q.deutsch.21': 'What is intertextuality?', 'lz.q.deutsch.22': 'What is Weimar Classicism?', 'lz.q.deutsch.23': 'How to write a character analysis?', 'lz.q.deutsch.24': 'What is an interior monologue?', 'lz.q.deutsch.25': 'What types of sentences exist?', 'lz.q.deutsch.26': 'Features of the Enlightenment?', 'lz.q.deutsch.27': 'What is a novella?', 'lz.q.deutsch.28': 'How to argue convincingly?', 'lz.q.deutsch.29': 'What is a leitmotif?',
  'lz.q.englisch.0': 'Difference between "since" and "for"?', 'lz.q.englisch.1': 'How to form the passive voice?', 'lz.q.englisch.2': 'What is conditional III?', 'lz.q.englisch.3': 'How to write a summary?', 'lz.q.englisch.4': 'What is the American Dream?', 'lz.q.englisch.5': 'When to use present perfect?', 'lz.q.englisch.6': 'What are collocations?', 'lz.q.englisch.7': 'How to analyse a political speech?', 'lz.q.englisch.8': 'What is indirect speech?', 'lz.q.englisch.9': 'What does globalisation mean?', 'lz.q.englisch.10': 'How to write a comment?', 'lz.q.englisch.11': 'What are linking words?', 'lz.q.englisch.12': 'British vs. American English?', 'lz.q.englisch.13': 'How to mediate a text?', 'lz.q.englisch.14': 'What is a dystopia?', 'lz.q.englisch.15': 'What are modal verbs for?', 'lz.q.englisch.16': 'How to interpret a cartoon?', 'lz.q.englisch.17': 'UK political system?', 'lz.q.englisch.18': 'How to write a letter to the editor?', 'lz.q.englisch.19': 'What is multiculturalism?', 'lz.q.englisch.20': 'Gerund vs. infinitive?', 'lz.q.englisch.21': 'Protagonist vs. antagonist?', 'lz.q.englisch.22': 'How to describe a diagram?', 'lz.q.englisch.23': 'What is cultural identity?', 'lz.q.englisch.24': 'What are phrasal verbs?', 'lz.q.englisch.25': 'How to write a blog entry?', 'lz.q.englisch.26': 'What is the Commonwealth?', 'lz.q.englisch.27': 'What does sustainability mean?', 'lz.q.englisch.28': 'How to use relative clauses?', 'lz.q.englisch.29': '"Make" vs. "do"?',
  'lz.q.ethik.0': 'What is the categorical imperative?', 'lz.q.ethik.1': 'Morality vs. ethics?', 'lz.q.ethik.2': 'What is utilitarianism?', 'lz.q.ethik.3': 'What does human dignity mean?', 'lz.q.ethik.4': 'Aristotle\'s virtue ethics?', 'lz.q.ethik.5': 'What is justice?', 'lz.q.ethik.6': 'What is the trolley problem?', 'lz.q.ethik.7': 'What is contractualism?', 'lz.q.ethik.8': 'What is free will?', 'lz.q.ethik.9': 'Jonas\' concept of responsibility?', 'lz.q.ethik.10': 'Hobbes\' state of nature?', 'lz.q.ethik.11': 'The euthanasia debate?', 'lz.q.ethik.12': 'What is an ethical dilemma?', 'lz.q.ethik.13': 'How does Kant\'s deontology work?', 'lz.q.ethik.14': 'What are human rights?', 'lz.q.ethik.15': 'What is conscience?', 'lz.q.ethik.16': 'Act vs. rule utilitarianism?', 'lz.q.ethik.17': 'What is ethical relativism?', 'lz.q.ethik.18': 'What does autonomy mean?', 'lz.q.ethik.19': 'What is the Golden Rule?', 'lz.q.ethik.20': 'Rawls\' veil of ignorance?', 'lz.q.ethik.21': 'What is bioethics?', 'lz.q.ethik.22': 'Sustainability from an ethical view?', 'lz.q.ethik.23': 'What is discourse ethics?', 'lz.q.ethik.24': 'What is tolerance?', 'lz.q.ethik.25': 'Law vs. morality?', 'lz.q.ethik.26': 'What is animal ethics?', 'lz.q.ethik.27': 'What does solidarity mean?', 'lz.q.ethik.28': 'Ethical dilemmas of AI?', 'lz.q.ethik.29': 'Freedom according to Kant?',
  'lz.q.geschichte.0': 'What was industrialisation?', 'lz.q.geschichte.1': 'The Weimar Constitution?', 'lz.q.geschichte.2': 'How did Hitler rise to power?', 'lz.q.geschichte.3': 'The founding of the German Empire 1871?', 'lz.q.geschichte.4': 'What is separation of powers?', 'lz.q.geschichte.5': 'What was the Cold War?', 'lz.q.geschichte.6': 'Democracy vs. dictatorship?', 'lz.q.geschichte.7': 'The Treaty of Versailles?', 'lz.q.geschichte.8': 'What is federalism?', 'lz.q.geschichte.9': 'The division of Germany?', 'lz.q.geschichte.10': 'What is the welfare state?', 'lz.q.geschichte.11': 'The Revolution of 1848?', 'lz.q.geschichte.12': 'What is NATO?', 'lz.q.geschichte.13': 'What was denazification?', 'lz.q.geschichte.14': 'European integration?', 'lz.q.geschichte.15': 'The Great Depression 1929?', 'lz.q.geschichte.16': 'What is the Basic Law?', 'lz.q.geschichte.17': 'November Revolution 1918?', 'lz.q.geschichte.18': 'What is imperialism?', 'lz.q.geschichte.19': 'The fall of the Berlin Wall 1989?', 'lz.q.geschichte.20': 'What is a constitution?', 'lz.q.geschichte.21': 'The Marshall Plan?', 'lz.q.geschichte.22': 'What is nationalism?', 'lz.q.geschichte.23': 'What was Gleichschaltung?', 'lz.q.geschichte.24': 'What does sovereignty mean?', 'lz.q.geschichte.25': 'Brandt\'s Ostpolitik?', 'lz.q.geschichte.26': 'Germany\'s electoral system?', 'lz.q.geschichte.27': 'The formation of blocs?', 'lz.q.geschichte.28': 'What is parliamentarism?', 'lz.q.geschichte.29': 'What was "Zero Hour"?',
  'lz.q.informatik.0': 'TCP vs. UDP?', 'lz.q.informatik.1': 'How does a binary tree work?', 'lz.q.informatik.2': 'What is database normalization?', 'lz.q.informatik.3': 'What is the OSI model?', 'lz.q.informatik.4': 'How does an SQL query work?', 'lz.q.informatik.5': 'What is OOP?', 'lz.q.informatik.6': 'What is an IP address?', 'lz.q.informatik.7': 'How does encryption work?', 'lz.q.informatik.8': 'What is an algorithm?', 'lz.q.informatik.9': 'Stack vs. queue?', 'lz.q.informatik.10': 'What is a network protocol?', 'lz.q.informatik.11': 'How does DNS work?', 'lz.q.informatik.12': 'What is recursion?', 'lz.q.informatik.13': 'What is a VLAN?', 'lz.q.informatik.14': 'What is an array?', 'lz.q.informatik.15': 'How does HTTP/HTTPS work?', 'lz.q.informatik.16': 'What is an ER diagram?', 'lz.q.informatik.17': 'What is Big O notation?', 'lz.q.informatik.18': 'What is a firewall?', 'lz.q.informatik.19': 'What are access rights?', 'lz.q.informatik.20': 'What is a subnet?', 'lz.q.informatik.21': 'How does a for loop work?', 'lz.q.informatik.22': 'What is an API?', 'lz.q.informatik.23': 'What is a primary key?', 'lz.q.informatik.24': 'Client-server architecture?', 'lz.q.informatik.25': 'Compiler vs. interpreter?', 'lz.q.informatik.26': 'What is phishing?', 'lz.q.informatik.27': 'What is a variable?', 'lz.q.informatik.28': 'What is routing?', 'lz.q.informatik.29': 'What is a class in Java?',
  'lz.q.spanisch.0': 'Difference between ser and estar?', 'lz.q.spanisch.1': 'How to form the subjunctive?', 'lz.q.spanisch.2': 'What is the indefinite preterite?', 'lz.q.spanisch.3': 'How to use "por" and "para"?', 'lz.q.spanisch.4': 'What are relative pronouns?', 'lz.q.spanisch.5': 'How to form the conditional?', 'lz.q.spanisch.6': 'What is an argumentative text?', 'lz.q.spanisch.7': 'Which past tenses exist?', 'lz.q.spanisch.8': 'The gerund in Spanish?', 'lz.q.spanisch.9': 'Direct and indirect object pronouns?', 'lz.q.spanisch.10': 'Passive voice in Spanish?', 'lz.q.spanisch.11': 'What are text connectors?', 'lz.q.spanisch.12': 'How to form the imperative?', 'lz.q.spanisch.13': 'How to write a summary?', 'lz.q.spanisch.14': 'Spain vs. Latin America?', 'lz.q.spanisch.15': 'What is the simple future?', 'lz.q.spanisch.16': 'How to analyse a literary text?', 'lz.q.spanisch.17': 'What are reflexive verbs?', 'lz.q.spanisch.18': 'How to express wishes?', 'lz.q.spanisch.19': 'What is the pluperfect?', 'lz.q.spanisch.20': 'Adverbs of frequency?', 'lz.q.spanisch.21': '"Aunque" with indicative/subjunctive?', 'lz.q.spanisch.22': 'Relevant social topics?', 'lz.q.spanisch.23': 'How to describe an image?', 'lz.q.spanisch.24': 'Immigration in Spain?', 'lz.q.spanisch.25': 'Conditional sentences?', 'lz.q.spanisch.26': 'What is indirect speech?', 'lz.q.spanisch.27': 'False cognates?', 'lz.q.spanisch.28': 'How to write a formal letter?', 'lz.q.spanisch.29': 'What is the imperfect?',
  'lz.q.sport.0': 'What is supercompensation?', 'lz.q.sport.1': 'Types of endurance?', 'lz.q.sport.2': 'Maximum heart rate?', 'lz.q.sport.3': 'How does muscle contraction work?', 'lz.q.sport.4': 'Strength vs. speed?', 'lz.q.sport.5': 'What is coordination?', 'lz.q.sport.6': 'Energy supply pathways?', 'lz.q.sport.7': 'The training pyramid?', 'lz.q.sport.8': 'What is motor learning?', 'lz.q.sport.9': 'Load-recovery model?', 'lz.q.sport.10': 'Basic motor abilities?', 'lz.q.sport.11': 'What is periodization?', 'lz.q.sport.12': 'Aerobic metabolism?', 'lz.q.sport.13': 'What is flexibility?', 'lz.q.sport.14': 'Stretching vs. mobilising?', 'lz.q.sport.15': 'Progressive overload?', 'lz.q.sport.16': 'Types of joints?', 'lz.q.sport.17': 'What is lactate?', 'lz.q.sport.18': 'Sport motor tests?', 'lz.q.sport.19': 'What is mental training?', 'lz.q.sport.20': 'Nutrition and performance?', 'lz.q.sport.21': 'What is proprioception?', 'lz.q.sport.22': 'Principles of training?', 'lz.q.sport.23': 'What is recovery?', 'lz.q.sport.24': 'How does doping work?', 'lz.q.sport.25': 'What is BMI?', 'lz.q.sport.26': 'Functional training?', 'lz.q.sport.27': 'Types of muscle fibres?', 'lz.q.sport.28': 'Anaerobic threshold?', 'lz.q.sport.29': 'What does fair play mean?',
};

// ══════════════════════════════════════════════════════════
// RUSSISCH
// ══════════════════════════════════════════════════════════

export const questionsRU = {
  'lz.q.chemie.0': 'Что описывает модель атома Бора?', 'lz.q.chemie.1': 'Чем различаются σ- и π-связи?', 'lz.q.chemie.2': 'Что такое экзотермическая реакция?', 'lz.q.chemie.3': 'Какова функция катализатора?', 'lz.q.chemie.4': 'Что гласит принцип Ле Шателье?', 'lz.q.chemie.5': 'Окисление vs. восстановление?', 'lz.q.chemie.6': 'Как устроена таблица Менделеева?', 'lz.q.chemie.7': 'Что такое силы Ван-дер-Ваальса?', 'lz.q.chemie.8': 'Что такое гальванический элемент?', 'lz.q.chemie.9': 'Как рассчитать pH?', 'lz.q.chemie.10': 'Что такое кислота по Бренстеду?', 'lz.q.chemie.11': 'Что такое гибридизация?', 'lz.q.chemie.12': 'Как работает электролиз?', 'lz.q.chemie.13': 'Что такое моль?', 'lz.q.chemie.14': 'Для чего нужно титрование?', 'lz.q.chemie.15': 'Что такое функциональные группы?', 'lz.q.chemie.16': 'Уравнение идеального газа?', 'lz.q.chemie.17': 'Виды изомерии?', 'lz.q.chemie.18': 'Что описывает энтальпия?', 'lz.q.chemie.19': 'Что такое буферный раствор?', 'lz.q.chemie.20': 'Как работает индикатор?', 'lz.q.chemie.21': 'Что такое правило октета?', 'lz.q.chemie.22': 'Какие типы связей существуют?', 'lz.q.chemie.23': 'Спирты, альдегиды, кетоны?', 'lz.q.chemie.24': 'Что происходит при этерификации?', 'lz.q.chemie.25': 'Что такое ОВР?', 'lz.q.chemie.26': 'Как влияет электроотрицательность?', 'lz.q.chemie.27': 'Что такое диполь?', 'lz.q.chemie.28': 'Как образуется водородная связь?', 'lz.q.chemie.29': 'Атом vs. ион?',
  'lz.q.deutsch.0': 'Четыре стороны сообщения?', 'lz.q.deutsch.1': 'Как анализировать рассказ?', 'lz.q.deutsch.2': 'Эпос vs. драма?', 'lz.q.deutsch.3': 'Черты романтизма?', 'lz.q.deutsch.4': 'Что такое лирическое «я»?', 'lz.q.deutsch.5': 'Структура линейного эссе?', 'lz.q.deutsch.6': 'Теория коммуникации Вацлавика?', 'lz.q.deutsch.7': 'Какие перспективы повествования существуют?', 'lz.q.deutsch.8': 'Черты экспрессионизма?', 'lz.q.deutsch.9': 'Как писать интерпретацию?', 'lz.q.deutsch.10': 'Что такое художественный образ?', 'lz.q.deutsch.11': 'Зачем нужен Konjunktiv II?', 'lz.q.deutsch.12': 'Что такое «Буря и натиск»?', 'lz.q.deutsch.13': 'Как анализировать публицистику?', 'lz.q.deutsch.14': 'Текстовое рассуждение?', 'lz.q.deutsch.15': 'Роль рассказчика?', 'lz.q.deutsch.16': 'Что такое смена эпох?', 'lz.q.deutsch.17': 'Как анализировать драму?', 'lz.q.deutsch.18': 'Что такое риторические средства?', 'lz.q.deutsch.19': 'Басня vs. притча?', 'lz.q.deutsch.20': 'Формальный анализ стихотворения?', 'lz.q.deutsch.21': 'Что такое интертекстуальность?', 'lz.q.deutsch.22': 'Веймарский классицизм?', 'lz.q.deutsch.23': 'Как писать характеристику?', 'lz.q.deutsch.24': 'Что такое внутренний монолог?', 'lz.q.deutsch.25': 'Какие типы предложений существуют?', 'lz.q.deutsch.26': 'Черты эпохи Просвещения?', 'lz.q.deutsch.27': 'Что такое новелла?', 'lz.q.deutsch.28': 'Как убедительно аргументировать?', 'lz.q.deutsch.29': 'Что такое лейтмотив?',
  'lz.q.englisch.0': 'Разница между "since" и "for"?', 'lz.q.englisch.1': 'Как образовать пассивный залог?', 'lz.q.englisch.2': 'Условное предложение III типа?', 'lz.q.englisch.3': 'Как писать резюме?', 'lz.q.englisch.4': 'Что такое американская мечта?', 'lz.q.englisch.5': 'Когда используется Present Perfect?', 'lz.q.englisch.6': 'Что такое коллокации?', 'lz.q.englisch.7': 'Как анализировать политическую речь?', 'lz.q.englisch.8': 'Что такое косвенная речь?', 'lz.q.englisch.9': 'Что значит глобализация?', 'lz.q.englisch.10': 'Как писать комментарий?', 'lz.q.englisch.11': 'Что такое связующие слова?', 'lz.q.englisch.12': 'Британский vs. американский?', 'lz.q.englisch.13': 'Как медиировать текст?', 'lz.q.englisch.14': 'Что такое антиутопия?', 'lz.q.englisch.15': 'Для чего модальные глаголы?', 'lz.q.englisch.16': 'Как интерпретировать карикатуру?', 'lz.q.englisch.17': 'Политическая система Великобритании?', 'lz.q.englisch.18': 'Как написать письмо в редакцию?', 'lz.q.englisch.19': 'Что такое мультикультурализм?', 'lz.q.englisch.20': 'Герундий vs. инфинитив?', 'lz.q.englisch.21': 'Протагонист vs. антагонист?', 'lz.q.englisch.22': 'Как описать диаграмму?', 'lz.q.englisch.23': 'Культурная идентичность?', 'lz.q.englisch.24': 'Что такое фразовые глаголы?', 'lz.q.englisch.25': 'Как написать блог?', 'lz.q.englisch.26': 'Что такое Содружество?', 'lz.q.englisch.27': 'Что значит устойчивое развитие?', 'lz.q.englisch.28': 'Относительные придаточные?', 'lz.q.englisch.29': '"Make" vs. "do"?',
  'lz.q.ethik.0': 'Что такое категорический императив?', 'lz.q.ethik.1': 'Мораль vs. этика?', 'lz.q.ethik.2': 'Что такое утилитаризм?', 'lz.q.ethik.3': 'Что значит достоинство человека?', 'lz.q.ethik.4': 'Этика добродетелей Аристотеля?', 'lz.q.ethik.5': 'Что такое справедливость?', 'lz.q.ethik.6': 'Проблема вагонетки?', 'lz.q.ethik.7': 'Что такое контрактуализм?', 'lz.q.ethik.8': 'Что такое свобода воли?', 'lz.q.ethik.9': 'Ответственность по Йонасу?', 'lz.q.ethik.10': 'Естественное состояние по Гоббсу?', 'lz.q.ethik.11': 'Дебаты об эвтаназии?', 'lz.q.ethik.12': 'Что такое этическая дилемма?', 'lz.q.ethik.13': 'Деонтология Канта?', 'lz.q.ethik.14': 'Что такое права человека?', 'lz.q.ethik.15': 'Что такое совесть?', 'lz.q.ethik.16': 'Утилитаризм действия vs. правила?', 'lz.q.ethik.17': 'Этический релятивизм?', 'lz.q.ethik.18': 'Что значит автономия?', 'lz.q.ethik.19': 'Золотое правило?', 'lz.q.ethik.20': 'Завеса неведения Ролза?', 'lz.q.ethik.21': 'Что такое биоэтика?', 'lz.q.ethik.22': 'Устойчивое развитие и этика?', 'lz.q.ethik.23': 'Что такое дискурсивная этика?', 'lz.q.ethik.24': 'Что такое толерантность?', 'lz.q.ethik.25': 'Право vs. мораль?', 'lz.q.ethik.26': 'Этика отношения к животным?', 'lz.q.ethik.27': 'Что значит солидарность?', 'lz.q.ethik.28': 'Этические дилеммы ИИ?', 'lz.q.ethik.29': 'Свобода по Канту?',
  'lz.q.geschichte.0': 'Что такое индустриализация?', 'lz.q.geschichte.1': 'Веймарская конституция?', 'lz.q.geschichte.2': 'Как Гитлер пришёл к власти?', 'lz.q.geschichte.3': 'Образование Германской империи 1871?', 'lz.q.geschichte.4': 'Что такое разделение властей?', 'lz.q.geschichte.5': 'Что такое холодная война?', 'lz.q.geschichte.6': 'Демократия vs. диктатура?', 'lz.q.geschichte.7': 'Версальский договор?', 'lz.q.geschichte.8': 'Что такое федерализм?', 'lz.q.geschichte.9': 'Раздел Германии?', 'lz.q.geschichte.10': 'Что такое социальное государство?', 'lz.q.geschichte.11': 'Революция 1848 года?', 'lz.q.geschichte.12': 'Что такое НАТО?', 'lz.q.geschichte.13': 'Что такое денацификация?', 'lz.q.geschichte.14': 'Европейская интеграция?', 'lz.q.geschichte.15': 'Мировой экономический кризис 1929?', 'lz.q.geschichte.16': 'Что такое Основной закон?', 'lz.q.geschichte.17': 'Ноябрьская революция 1918?', 'lz.q.geschichte.18': 'Что такое империализм?', 'lz.q.geschichte.19': 'Падение Берлинской стены 1989?', 'lz.q.geschichte.20': 'Что такое конституция?', 'lz.q.geschichte.21': 'План Маршалла?', 'lz.q.geschichte.22': 'Что такое национализм?', 'lz.q.geschichte.23': 'Что такое унификация?', 'lz.q.geschichte.24': 'Что значит суверенитет?', 'lz.q.geschichte.25': 'Восточная политика Брандта?', 'lz.q.geschichte.26': 'Избирательная система ФРГ?', 'lz.q.geschichte.27': 'Формирование блоков?', 'lz.q.geschichte.28': 'Что такое парламентаризм?', 'lz.q.geschichte.29': 'Что такое «нулевой час»?',
  'lz.q.informatik.0': 'TCP vs. UDP?', 'lz.q.informatik.1': 'Как работает бинарное дерево?', 'lz.q.informatik.2': 'Нормальные формы БД?', 'lz.q.informatik.3': 'Что такое модель OSI?', 'lz.q.informatik.4': 'Как работает SQL-запрос?', 'lz.q.informatik.5': 'Что такое ООП?', 'lz.q.informatik.6': 'Что такое IP-адрес?', 'lz.q.informatik.7': 'Как работает шифрование?', 'lz.q.informatik.8': 'Что такое алгоритм?', 'lz.q.informatik.9': 'Стек vs. очередь?', 'lz.q.informatik.10': 'Что такое сетевой протокол?', 'lz.q.informatik.11': 'Как работает DNS?', 'lz.q.informatik.12': 'Что такое рекурсия?', 'lz.q.informatik.13': 'Что такое VLAN?', 'lz.q.informatik.14': 'Что такое массив?', 'lz.q.informatik.15': 'Как работает HTTP/HTTPS?', 'lz.q.informatik.16': 'Что такое ER-диаграмма?', 'lz.q.informatik.17': 'Что такое О-нотация?', 'lz.q.informatik.18': 'Что такое файрвол?', 'lz.q.informatik.19': 'Что такое права доступа?', 'lz.q.informatik.20': 'Что такое подсеть?', 'lz.q.informatik.21': 'Как работает цикл for?', 'lz.q.informatik.22': 'Что такое API?', 'lz.q.informatik.23': 'Что такое первичный ключ?', 'lz.q.informatik.24': 'Клиент-серверная архитектура?', 'lz.q.informatik.25': 'Компилятор vs. интерпретатор?', 'lz.q.informatik.26': 'Что такое фишинг?', 'lz.q.informatik.27': 'Что такое переменная?', 'lz.q.informatik.28': 'Что такое маршрутизация?', 'lz.q.informatik.29': 'Что такое класс в Java?',
  'lz.q.spanisch.0': 'Разница между ser и estar?', 'lz.q.spanisch.1': 'Как образовать субхунтиво?', 'lz.q.spanisch.2': 'Pretérito indefinido?', 'lz.q.spanisch.3': 'Как использовать por и para?', 'lz.q.spanisch.4': 'Относительные местоимения?', 'lz.q.spanisch.5': 'Как образовать условное наклонение?', 'lz.q.spanisch.6': 'Аргументативный текст?', 'lz.q.spanisch.7': 'Какие прошедшие времена есть?', 'lz.q.spanisch.8': 'Герундий в испанском?', 'lz.q.spanisch.9': 'Местоимения прямого и косвенного дополнения?', 'lz.q.spanisch.10': 'Пассивный залог в испанском?', 'lz.q.spanisch.11': 'Текстовые связки?', 'lz.q.spanisch.12': 'Как образовать повелительное наклонение?', 'lz.q.spanisch.13': 'Как писать резюме?', 'lz.q.spanisch.14': 'Испания vs. Латинская Америка?', 'lz.q.spanisch.15': 'Простое будущее время?', 'lz.q.spanisch.16': 'Анализ литературного текста?', 'lz.q.spanisch.17': 'Возвратные глаголы?', 'lz.q.spanisch.18': 'Как выражать желания?', 'lz.q.spanisch.19': 'Плюсквамперфект?', 'lz.q.spanisch.20': 'Наречия частотности?', 'lz.q.spanisch.21': '"Aunque" с индикативом и субхунтиво?', 'lz.q.spanisch.22': 'Актуальные социальные темы?', 'lz.q.spanisch.23': 'Как описать изображение?', 'lz.q.spanisch.24': 'Иммиграция в Испании?', 'lz.q.spanisch.25': 'Условные предложения?', 'lz.q.spanisch.26': 'Косвенная речь?', 'lz.q.spanisch.27': 'Ложные друзья переводчика?', 'lz.q.spanisch.28': 'Как написать официальное письмо?', 'lz.q.spanisch.29': 'Pretérito imperfecto?',
  'lz.q.sport.0': 'Принцип суперкомпенсации?', 'lz.q.sport.1': 'Виды выносливости?', 'lz.q.sport.2': 'Максимальная ЧСС?', 'lz.q.sport.3': 'Как работает сокращение мышц?', 'lz.q.sport.4': 'Сила vs. скорость?', 'lz.q.sport.5': 'Что такое координация?', 'lz.q.sport.6': 'Пути энергообеспечения?', 'lz.q.sport.7': 'Пирамида тренировок?', 'lz.q.sport.8': 'Что такое моторное обучение?', 'lz.q.sport.9': 'Модель нагрузка-восстановление?', 'lz.q.sport.10': 'Базовые двигательные качества?', 'lz.q.sport.11': 'Что такое периодизация?', 'lz.q.sport.12': 'Аэробный обмен веществ?', 'lz.q.sport.13': 'Что такое гибкость?', 'lz.q.sport.14': 'Растяжка vs. мобилизация?', 'lz.q.sport.15': 'Принцип прогрессивной нагрузки?', 'lz.q.sport.16': 'Типы суставов?', 'lz.q.sport.17': 'Что такое лактат?', 'lz.q.sport.18': 'Спортивные двигательные тесты?', 'lz.q.sport.19': 'Ментальная тренировка?', 'lz.q.sport.20': 'Питание и результат?', 'lz.q.sport.21': 'Что такое проприоцепция?', 'lz.q.sport.22': 'Принципы тренировки?', 'lz.q.sport.23': 'Что такое восстановление?', 'lz.q.sport.24': 'Как действует допинг?', 'lz.q.sport.25': 'Что такое ИМТ?', 'lz.q.sport.26': 'Функциональная тренировка?', 'lz.q.sport.27': 'Типы мышечных волокон?', 'lz.q.sport.28': 'Анаэробный порог?', 'lz.q.sport.29': 'Что такое фэйр-плей?',
};

// ══════════════════════════════════════════════════════════
// SPANISCH
// ══════════════════════════════════════════════════════════

export const questionsES = {
  'lz.q.chemie.0': '¿Qué describe el modelo atómico de Bohr?', 'lz.q.chemie.1': '¿Diferencia entre enlaces σ y π?', 'lz.q.chemie.2': '¿Qué es una reacción exotérmica?', 'lz.q.chemie.3': '¿Función de un catalizador?', 'lz.q.chemie.4': '¿Principio de Le Chatelier?', 'lz.q.chemie.5': '¿Oxidación vs. reducción?', 'lz.q.chemie.6': '¿Estructura de la tabla periódica?', 'lz.q.chemie.7': '¿Fuerzas de Van der Waals?', 'lz.q.chemie.8': '¿Qué es una pila galvánica?', 'lz.q.chemie.9': '¿Cómo calcular el pH?', 'lz.q.chemie.10': '¿Ácido según Brønsted?', 'lz.q.chemie.11': '¿Qué es la hibridación?', 'lz.q.chemie.12': '¿Cómo funciona la electrólisis?', 'lz.q.chemie.13': '¿Qué es un mol?', 'lz.q.chemie.14': '¿Para qué sirve la titulación?', 'lz.q.chemie.15': '¿Grupos funcionales?', 'lz.q.chemie.16': '¿Ley de los gases ideales?', 'lz.q.chemie.17': '¿Tipos de isomería?', 'lz.q.chemie.18': '¿Qué describe la entalpía?', 'lz.q.chemie.19': '¿Solución amortiguadora?', 'lz.q.chemie.20': '¿Cómo funciona un indicador?', 'lz.q.chemie.21': '¿Regla del octeto?', 'lz.q.chemie.22': '¿Tipos de enlaces?', 'lz.q.chemie.23': '¿Alcoholes, aldehídos, cetonas?', 'lz.q.chemie.24': '¿Qué pasa en la esterificación?', 'lz.q.chemie.25': '¿Reacción redox?', 'lz.q.chemie.26': '¿Efecto de la electronegatividad?', 'lz.q.chemie.27': '¿Qué es un dipolo?', 'lz.q.chemie.28': '¿Puentes de hidrógeno?', 'lz.q.chemie.29': '¿Átomo vs. ion?',
  'lz.q.deutsch.0': '¿Las cuatro caras de un mensaje?', 'lz.q.deutsch.1': '¿Cómo analizar un relato corto?', 'lz.q.deutsch.2': '¿Épica vs. dramática?', 'lz.q.deutsch.3': '¿Características del romanticismo?', 'lz.q.deutsch.4': '¿Qué es el yo lírico?', 'lz.q.deutsch.5': '¿Estructura de un ensayo lineal?', 'lz.q.deutsch.6': '¿Teoría de Watzlawick?', 'lz.q.deutsch.7': '¿Perspectivas narrativas?', 'lz.q.deutsch.8': '¿Rasgos del expresionismo?', 'lz.q.deutsch.9': '¿Cómo escribir una interpretación?', 'lz.q.deutsch.10': '¿Qué es una figura retórica?', 'lz.q.deutsch.11': '¿Para qué sirve el Konjunktiv II?', 'lz.q.deutsch.12': '¿Qué es Sturm und Drang?', 'lz.q.deutsch.13': '¿Cómo analizar textos expositivos?', 'lz.q.deutsch.14': '¿Ensayo basado en texto?', 'lz.q.deutsch.15': '¿Rol del narrador?', 'lz.q.deutsch.16': '¿Cambio de época?', 'lz.q.deutsch.17': '¿Análisis dramático?', 'lz.q.deutsch.18': '¿Recursos retóricos?', 'lz.q.deutsch.19': '¿Fábula vs. parábola?', 'lz.q.deutsch.20': '¿Análisis formal de un poema?', 'lz.q.deutsch.21': '¿Qué es la intertextualidad?', 'lz.q.deutsch.22': '¿Clasicismo de Weimar?', 'lz.q.deutsch.23': '¿Cómo hacer una caracterización?', 'lz.q.deutsch.24': '¿Monólogo interior?', 'lz.q.deutsch.25': '¿Tipos de oraciones?', 'lz.q.deutsch.26': '¿Características de la Ilustración?', 'lz.q.deutsch.27': '¿Qué es una novela corta?', 'lz.q.deutsch.28': '¿Cómo argumentar de forma convincente?', 'lz.q.deutsch.29': '¿Qué es un leitmotiv?',
  'lz.q.englisch.0': '¿Diferencia entre "since" y "for"?', 'lz.q.englisch.1': '¿Voz pasiva en inglés?', 'lz.q.englisch.2': '¿Condicional tipo III?', 'lz.q.englisch.3': '¿Cómo escribir un resumen?', 'lz.q.englisch.4': '¿Qué es el Sueño Americano?', 'lz.q.englisch.5': '¿Cuándo usar Present Perfect?', 'lz.q.englisch.6': '¿Qué son las colocaciones?', 'lz.q.englisch.7': '¿Análisis de un discurso político?', 'lz.q.englisch.8': '¿Discurso indirecto?', 'lz.q.englisch.9': '¿Qué significa globalización?', 'lz.q.englisch.10': '¿Cómo escribir un comentario?', 'lz.q.englisch.11': '¿Conectores textuales?', 'lz.q.englisch.12': '¿Inglés británico vs. americano?', 'lz.q.englisch.13': '¿Cómo mediar un texto?', 'lz.q.englisch.14': '¿Qué es una distopía?', 'lz.q.englisch.15': '¿Verbos modales?', 'lz.q.englisch.16': '¿Interpretar una caricatura?', 'lz.q.englisch.17': '¿Sistema político del Reino Unido?', 'lz.q.englisch.18': '¿Carta al editor?', 'lz.q.englisch.19': '¿Multiculturalismo?', 'lz.q.englisch.20': '¿Gerundio vs. infinitivo?', 'lz.q.englisch.21': '¿Protagonista vs. antagonista?', 'lz.q.englisch.22': '¿Describir un diagrama?', 'lz.q.englisch.23': '¿Identidad cultural?', 'lz.q.englisch.24': '¿Phrasal verbs?', 'lz.q.englisch.25': '¿Escribir un blog?', 'lz.q.englisch.26': '¿Qué es la Commonwealth?', 'lz.q.englisch.27': '¿Qué significa sostenibilidad?', 'lz.q.englisch.28': '¿Cláusulas relativas?', 'lz.q.englisch.29': '¿"Make" vs. "do"?',
  'lz.q.ethik.0': '¿Imperativo categórico?', 'lz.q.ethik.1': '¿Moral vs. ética?', 'lz.q.ethik.2': '¿Utilitarismo?', 'lz.q.ethik.3': '¿Dignidad humana?', 'lz.q.ethik.4': '¿Ética de virtudes de Aristóteles?', 'lz.q.ethik.5': '¿Qué es la justicia?', 'lz.q.ethik.6': '¿Problema del tranvía?', 'lz.q.ethik.7': '¿Contractualismo?', 'lz.q.ethik.8': '¿Libre albedrío?', 'lz.q.ethik.9': '¿Responsabilidad según Jonas?', 'lz.q.ethik.10': '¿Estado de naturaleza de Hobbes?', 'lz.q.ethik.11': '¿Debate sobre eutanasia?', 'lz.q.ethik.12': '¿Dilema ético?', 'lz.q.ethik.13': '¿Deontología de Kant?', 'lz.q.ethik.14': '¿Derechos humanos?', 'lz.q.ethik.15': '¿Qué es la conciencia?', 'lz.q.ethik.16': '¿Utilitarismo de acto vs. regla?', 'lz.q.ethik.17': '¿Relativismo ético?', 'lz.q.ethik.18': '¿Qué es la autonomía?', 'lz.q.ethik.19': '¿Regla de oro?', 'lz.q.ethik.20': '¿Velo de ignorancia de Rawls?', 'lz.q.ethik.21': '¿Bioética?', 'lz.q.ethik.22': '¿Sostenibilidad y ética?', 'lz.q.ethik.23': '¿Ética del discurso?', 'lz.q.ethik.24': '¿Qué es la tolerancia?', 'lz.q.ethik.25': '¿Derecho vs. moral?', 'lz.q.ethik.26': '¿Ética animal?', 'lz.q.ethik.27': '¿Qué es la solidaridad?', 'lz.q.ethik.28': '¿Dilemas éticos de la IA?', 'lz.q.ethik.29': '¿Libertad según Kant?',
  'lz.q.geschichte.0': '¿Qué fue la industrialización?', 'lz.q.geschichte.1': '¿Constitución de Weimar?', 'lz.q.geschichte.2': '¿Cómo llegó Hitler al poder?', 'lz.q.geschichte.3': '¿Fundación del Imperio Alemán 1871?', 'lz.q.geschichte.4': '¿Separación de poderes?', 'lz.q.geschichte.5': '¿Qué fue la Guerra Fría?', 'lz.q.geschichte.6': '¿Democracia vs. dictadura?', 'lz.q.geschichte.7': '¿Tratado de Versalles?', 'lz.q.geschichte.8': '¿Qué es el federalismo?', 'lz.q.geschichte.9': '¿División de Alemania?', 'lz.q.geschichte.10': '¿Estado de bienestar?', 'lz.q.geschichte.11': '¿Revolución de 1848?', 'lz.q.geschichte.12': '¿Qué es la OTAN?', 'lz.q.geschichte.13': '¿Desnazificación?', 'lz.q.geschichte.14': '¿Integración europea?', 'lz.q.geschichte.15': '¿Crisis económica de 1929?', 'lz.q.geschichte.16': '¿Ley Fundamental?', 'lz.q.geschichte.17': '¿Revolución de noviembre 1918?', 'lz.q.geschichte.18': '¿Qué es el imperialismo?', 'lz.q.geschichte.19': '¿Caída del Muro 1989?', 'lz.q.geschichte.20': '¿Qué es una constitución?', 'lz.q.geschichte.21': '¿Plan Marshall?', 'lz.q.geschichte.22': '¿Nacionalismo?', 'lz.q.geschichte.23': '¿Gleichschaltung?', 'lz.q.geschichte.24': '¿Qué significa soberanía?', 'lz.q.geschichte.25': '¿Ostpolitik de Brandt?', 'lz.q.geschichte.26': '¿Sistema electoral alemán?', 'lz.q.geschichte.27': '¿Formación de bloques?', 'lz.q.geschichte.28': '¿Parlamentarismo?', 'lz.q.geschichte.29': '¿La "hora cero"?',
  'lz.q.informatik.0': '¿TCP vs. UDP?', 'lz.q.informatik.1': '¿Cómo funciona un árbol binario?', 'lz.q.informatik.2': '¿Formas normales de BD?', 'lz.q.informatik.3': '¿Modelo OSI?', 'lz.q.informatik.4': '¿Consultas SQL?', 'lz.q.informatik.5': '¿Qué es POO?', 'lz.q.informatik.6': '¿Dirección IP?', 'lz.q.informatik.7': '¿Cómo funciona el cifrado?', 'lz.q.informatik.8': '¿Qué es un algoritmo?', 'lz.q.informatik.9': '¿Pila vs. cola?', 'lz.q.informatik.10': '¿Protocolo de red?', 'lz.q.informatik.11': '¿Cómo funciona DNS?', 'lz.q.informatik.12': '¿Qué es la recursión?', 'lz.q.informatik.13': '¿Qué es una VLAN?', 'lz.q.informatik.14': '¿Qué es un array?', 'lz.q.informatik.15': '¿HTTP/HTTPS?', 'lz.q.informatik.16': '¿Diagrama ER?', 'lz.q.informatik.17': '¿Notación Big O?', 'lz.q.informatik.18': '¿Qué es un firewall?', 'lz.q.informatik.19': '¿Permisos de acceso?', 'lz.q.informatik.20': '¿Qué es una subred?', 'lz.q.informatik.21': '¿Bucle for?', 'lz.q.informatik.22': '¿Qué es una API?', 'lz.q.informatik.23': '¿Clave primaria?', 'lz.q.informatik.24': '¿Arquitectura cliente-servidor?', 'lz.q.informatik.25': '¿Compilador vs. intérprete?', 'lz.q.informatik.26': '¿Qué es phishing?', 'lz.q.informatik.27': '¿Qué es una variable?', 'lz.q.informatik.28': '¿Qué es el enrutamiento?', 'lz.q.informatik.29': '¿Clase en Java?',
  'lz.q.spanisch.0': '¿Diferencia entre ser y estar?', 'lz.q.spanisch.1': '¿Cómo se forma el subjuntivo?', 'lz.q.spanisch.2': '¿Pretérito indefinido?', 'lz.q.spanisch.3': '¿Uso de "por" y "para"?', 'lz.q.spanisch.4': '¿Pronombres relativos?', 'lz.q.spanisch.5': '¿Condicional?', 'lz.q.spanisch.6': '¿Texto argumentativo?', 'lz.q.spanisch.7': '¿Tiempos del pasado?', 'lz.q.spanisch.8': '¿Gerundio?', 'lz.q.spanisch.9': '¿Pronombres OD y OI?', 'lz.q.spanisch.10': '¿Voz pasiva?', 'lz.q.spanisch.11': '¿Conectores textuales?', 'lz.q.spanisch.12': '¿Imperativo?', 'lz.q.spanisch.13': '¿Cómo hacer un resumen?', 'lz.q.spanisch.14': '¿España vs. Latinoamérica?', 'lz.q.spanisch.15': '¿Futuro simple?', 'lz.q.spanisch.16': '¿Análisis literario?', 'lz.q.spanisch.17': '¿Verbos reflexivos?', 'lz.q.spanisch.18': '¿Expresar deseos?', 'lz.q.spanisch.19': '¿Pluscuamperfecto?', 'lz.q.spanisch.20': '¿Adverbios de frecuencia?', 'lz.q.spanisch.21': '¿"Aunque" indicativo/subjuntivo?', 'lz.q.spanisch.22': '¿Temas sociales?', 'lz.q.spanisch.23': '¿Describir una imagen?', 'lz.q.spanisch.24': '¿Inmigración en España?', 'lz.q.spanisch.25': '¿Oración condicional?', 'lz.q.spanisch.26': '¿Estilo indirecto?', 'lz.q.spanisch.27': '¿Falsos amigos?', 'lz.q.spanisch.28': '¿Carta formal?', 'lz.q.spanisch.29': '¿Pretérito imperfecto?',
  'lz.q.sport.0': '¿Principio de supercompensación?', 'lz.q.sport.1': '¿Tipos de resistencia?', 'lz.q.sport.2': '¿Frecuencia cardíaca máxima?', 'lz.q.sport.3': '¿Contracción muscular?', 'lz.q.sport.4': '¿Fuerza vs. velocidad?', 'lz.q.sport.5': '¿Qué es la coordinación?', 'lz.q.sport.6': '¿Vías de suministro energético?', 'lz.q.sport.7': '¿Pirámide de entrenamiento?', 'lz.q.sport.8': '¿Aprendizaje motor?', 'lz.q.sport.9': '¿Modelo carga-recuperación?', 'lz.q.sport.10': '¿Capacidades motrices básicas?', 'lz.q.sport.11': '¿Periodización?', 'lz.q.sport.12': '¿Metabolismo aeróbico?', 'lz.q.sport.13': '¿Qué es la flexibilidad?', 'lz.q.sport.14': '¿Estirar vs. movilizar?', 'lz.q.sport.15': '¿Sobrecarga progresiva?', 'lz.q.sport.16': '¿Tipos de articulaciones?', 'lz.q.sport.17': '¿Qué es el lactato?', 'lz.q.sport.18': '¿Tests motores deportivos?', 'lz.q.sport.19': '¿Entrenamiento mental?', 'lz.q.sport.20': '¿Nutrición y rendimiento?', 'lz.q.sport.21': '¿Propiocepción?', 'lz.q.sport.22': '¿Principios del entrenamiento?', 'lz.q.sport.23': '¿Qué es la recuperación?', 'lz.q.sport.24': '¿Cómo funciona el dopaje?', 'lz.q.sport.25': '¿Qué es el IMC?', 'lz.q.sport.26': '¿Entrenamiento funcional?', 'lz.q.sport.27': '¿Tipos de fibras musculares?', 'lz.q.sport.28': '¿Umbral anaeróbico?', 'lz.q.sport.29': '¿Qué significa juego limpio?',
};