// core/routes/faecher/chemie_routes.js

export const CHEMIE_TITLE_KEYS = {
  '/projekte/lernzettel/faecher/chemie':        'page.title.lz.chemie',
  '/projekte/lernzettel/faecher/chemie/themen/1/1-1': 'page.title.lz.chemie.1-1',
  '/projekte/lernzettel/faecher/chemie/themen/1/1-2': 'page.title.lz.chemie.1-2',
  '/projekte/lernzettel/faecher/chemie/themen/1/1-3': 'page.title.lz.chemie.1-3',
  '/projekte/lernzettel/faecher/chemie/themen/2/2-1': 'page.title.lz.chemie.2-1',
  '/projekte/lernzettel/faecher/chemie/themen/2/2-2': 'page.title.lz.chemie.2-2',
  '/projekte/lernzettel/faecher/chemie/themen/3/3-1': 'page.title.lz.chemie.3-1',
  '/projekte/lernzettel/faecher/chemie/themen/3/3-2': 'page.title.lz.chemie.3-2',
  '/projekte/lernzettel/faecher/chemie/themen/4/4-1': 'page.title.lz.chemie.4-1',
  '/projekte/lernzettel/faecher/chemie/themen/4/4-2': 'page.title.lz.chemie.4-2',
  '/projekte/lernzettel/faecher/chemie/themen/5/5-1': 'page.title.lz.chemie.5-1',
  '/projekte/lernzettel/faecher/chemie/themen/5/5-2': 'page.title.lz.chemie.5-2',
  '/projekte/lernzettel/faecher/chemie/themen/5/5-3': 'page.title.lz.chemie.5-3',
  '/projekte/lernzettel/faecher/chemie/themen/6/6-1': 'page.title.lz.chemie.6-1',
  '/projekte/lernzettel/faecher/chemie/themen/6/6-2': 'page.title.lz.chemie.6-2',
  '/projekte/lernzettel/faecher/chemie/themen/6/6-3': 'page.title.lz.chemie.6-3',
  '/projekte/lernzettel/faecher/chemie/themen/7/7-1': 'page.title.lz.chemie.7-1',
  '/projekte/lernzettel/faecher/chemie/themen/7/7-2': 'page.title.lz.chemie.7-2',
  '/projekte/lernzettel/faecher/chemie/themen/8/8-1': 'page.title.lz.chemie.8-1',
  '/projekte/lernzettel/faecher/chemie/themen/8/8-2': 'page.title.lz.chemie.8-2',
  '/projekte/lernzettel/faecher/chemie/themen/8/8-3': 'page.title.lz.chemie.8-3',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-1': 'page.title.lz.chemie.9-1',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-2': 'page.title.lz.chemie.9-2',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-3': 'page.title.lz.chemie.9-3',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-4': 'page.title.lz.chemie.9-4',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-5': 'page.title.lz.chemie.9-5',
  '/projekte/lernzettel/faecher/chemie/themen/9/9-6': 'page.title.lz.chemie.9-6',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-1': 'page.title.lz.chemie.10-1',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-2': 'page.title.lz.chemie.10-2',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-3': 'page.title.lz.chemie.10-3',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-4': 'page.title.lz.chemie.10-4',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-5': 'page.title.lz.chemie.10-5',
  '/projekte/lernzettel/faecher/chemie/themen/10/10-6': 'page.title.lz.chemie.10-6',
  '/projekte/lernzettel/faecher/chemie/themen/11/11-1': 'page.title.lz.chemie.11-1',
  '/projekte/lernzettel/faecher/chemie/themen/11/11-2': 'page.title.lz.chemie.11-2',
  '/projekte/lernzettel/faecher/chemie/themen/pse': 'page.title.lz.chemie.pse',
};

export const CHEMIE_ROUTES = {
  '/projekte/lernzettel/faecher/chemie': () => import('../../../pages/projekte/lernzettel/faecher/chemie/chemie.js'),
  '/projekte/lernzettel/faecher/chemie/themen/1/1-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/1/1-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/1/1-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/1/1-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/1/1-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/1/1-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/2/2-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/2/2-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/2/2-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/2/2-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/3/3-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/3/3-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/3/3-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/3/3-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/4/4-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/4/4-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/4/4-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/4/4-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/5/5-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/5/5-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/5/5-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/5/5-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/5/5-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/5/5-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/6/6-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/6/6-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/6/6-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/6/6-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/6/6-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/6/6-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/7/7-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/7/7-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/7/7-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/7/7-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/8/8-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/8/8-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/8/8-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/8/8-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/8/8-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/8/8-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-4': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-4.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-5': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-5.js'),
  '/projekte/lernzettel/faecher/chemie/themen/9/9-6': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/9/9-6.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-3': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-3.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-4': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-4.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-5': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-5.js'),
  '/projekte/lernzettel/faecher/chemie/themen/10/10-6': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/10/10-6.js'),
  '/projekte/lernzettel/faecher/chemie/themen/11/11-1': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/11/11-1.js'),
  '/projekte/lernzettel/faecher/chemie/themen/11/11-2': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/11/11-2.js'),
  '/projekte/lernzettel/faecher/chemie/themen/pse': () => import('../../../pages/projekte/lernzettel/faecher/chemie/themen/pse.js'),
};

export const CHEMIE_TITLE_TRANSLATION = {
  'page.title.lz.chemie': 'Chemie — Lernzettel',
  'page.title.lz.chemie.1-1': 'Die Chemie im Kanon der Naturwissenschaften',
  'page.title.lz.chemie.1-2': 'Denk- und Arbeitsweisen in der Chemie',
  'page.title.lz.chemie.1-3': 'Stöchiometrie',
  'page.title.lz.chemie.2-1': 'Kernchemie',
  'page.title.lz.chemie.2-2': 'Entstehung der Elemente',
  'page.title.lz.chemie.3-1': 'Atombau',
  'page.title.lz.chemie.3-2': 'Das Periodensystem der Elemente',
  'page.title.lz.chemie.4-1': 'Hauptbindungsarten',
  'page.title.lz.chemie.4-2': 'Besondere Wechselwirkungen zwischen Molekülen',
  'page.title.lz.chemie.5-1': 'Chemische Thermodynamik',
  'page.title.lz.chemie.5-2': 'Chemische Kinetik',
  'page.title.lz.chemie.5-3': 'Elektrochemische Prozesse',
  'page.title.lz.chemie.6-1': 'Das chemische Gleichgewicht',
  'page.title.lz.chemie.6-2': 'Beeinflussung des chemischen Gleichgewichts',
  'page.title.lz.chemie.6-3': 'Anwendungen des Massenwirkungsgesetzes',
  'page.title.lz.chemie.7-1': 'Säuren und Basen',
  'page.title.lz.chemie.7-2': 'Redoxreaktionen',
  'page.title.lz.chemie.8-1': 'Hauptgruppenelemente und Verbindungen',
  'page.title.lz.chemie.8-2': 'Eigenschaften der Nebengruppenelemente',
  'page.title.lz.chemie.8-3': 'Komplexchemie',
  'page.title.lz.chemie.9-1': 'Allgemeine Grundlagen der organischen Chemie',
  'page.title.lz.chemie.9-2': 'Aliphatische Kohlenwasserstoffe',
  'page.title.lz.chemie.9-3': 'Aromatische Kohlenwasserstoffe',
  'page.title.lz.chemie.9-4': 'Organische Verbindungen mit funktionellen Gruppen',
  'page.title.lz.chemie.9-5': 'Naturstoffe',
  'page.title.lz.chemie.9-6': 'Chemie in Biosystemen',
  'page.title.lz.chemie.10-1': 'Werkstoffe',
  'page.title.lz.chemie.10-2': 'Farbstoffe',
  'page.title.lz.chemie.10-3': 'Tenside und Waschmittel',
  'page.title.lz.chemie.10-4': 'Arzneimittel',
  'page.title.lz.chemie.10-5': 'Ausgewählte chemisch-technische Verfahren',
  'page.title.lz.chemie.10-6': 'Umweltbezogene Chemie',
  'page.title.lz.chemie.11-1': 'Klassische Analyseverfahren',
  'page.title.lz.chemie.11-2': 'Instrumentelle Analyseverfahren',
  'page.title.lz.chemie.pse': 'PSE — Periodensystem der Elemente',
};