// core/routes/faecher/deutsch_routes.js

export const DEUTSCH_TITLE_KEYS = {
  '/projekte/lernzettel/faecher/deutsch': 'page.title.lz.deutsch',
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/was-ist-sprache': 'page.title.lz.deutsch-was-ist-sprache',
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/leistung-funktion': 'page.title.lz.deutsch-leistung-funktion',
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachvarietaeten': 'page.title.lz.deutsch-sprachvarietaeten',
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachwandel': 'page.title.lz.deutsch-sprachwandel',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/epik': 'page.title.lz.deutsch-epik',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/dramatik': 'page.title.lz.deutsch-dramatik',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/lyrik': 'page.title.lz.deutsch-lyrik',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/sachtexte': 'page.title.lz.deutsch-sachtexte',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/reden': 'page.title.lz.deutsch-reden',
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/analyse': 'page.title.lz.deutsch-analyse',
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/argumentieren': 'page.title.lz.deutsch-argumentieren',
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/textgebunden': 'page.title.lz.deutsch-textgebunden',
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/dialektisch': 'page.title.lz.deutsch-dialektisch',
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/linear': 'page.title.lz.deutsch-linear',
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/klangfiguren': 'page.title.lz.deutsch-klangfiguren',
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/wortfiguren': 'page.title.lz.deutsch-wortfiguren',
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/satzfiguren': 'page.title.lz.deutsch-satzfiguren',
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/ironie': 'page.title.lz.deutsch-ironie',
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/analyse-methodik': 'page.title.lz.deutsch-analyse-methodik',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/mittelalter': 'page.title.lz.deutsch-mittelalter',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/barock-aufklaerung': 'page.title.lz.deutsch-barock-aufklaerung',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/klassik-romantik': 'page.title.lz.deutsch-klassik-romantik',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/realismus-naturalismus': 'page.title.lz.deutsch-realismus-naturalismus',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/expressionismus-exil': 'page.title.lz.deutsch-expressionismus-exil',
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/nachkrieg-gegenwart': 'page.title.lz.deutsch-nachkrieg-gegenwart',
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/hochsprache': 'page.title.lz.deutsch-hochsprache',
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/assertive': 'page.title.lz.deutsch-assertive',
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/direktive': 'page.title.lz.deutsch-direktive',
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/deklarative': 'page.title.lz.deutsch-deklarative',
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/merkmale': 'page.title.lz.deutsch-merkmale',
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/einleitung': 'page.title.lz.deutsch-einleitung',
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/erzaehltechnik': 'page.title.lz.deutsch-erzaehltechnik',
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/stilmittel-analyse': 'page.title.lz.deutsch-stilmittel-analyse',
};

export const DEUTSCH_ROUTES = {
  '/projekte/lernzettel/faecher/deutsch': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/deutsch.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/was-ist-sprache': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/sprache/was-ist-sprache.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/leistung-funktion': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/sprache/leistung-funktion.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachvarietaeten': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachvarietaeten.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachwandel': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/sprache/sprachwandel.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/epik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/epik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/dramatik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/dramatik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/lyrik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/lyrik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/sachtexte': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/sachtexte.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/reden': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/reden.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/gattungen/analyse': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/gattungen/analyse.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/argumentieren': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/eroertern/argumentieren.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/textgebunden': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/eroertern/textgebunden.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/dialektisch': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/eroertern/dialektisch.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/eroertern/linear': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/eroertern/linear.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/klangfiguren': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/stilmittel/klangfiguren.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/wortfiguren': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/stilmittel/wortfiguren.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/satzfiguren': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/stilmittel/satzfiguren.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/ironie': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/stilmittel/ironie.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/stilmittel/analyse-methodik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/stilmittel/analyse-methodik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/mittelalter': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/mittelalter.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/barock-aufklaerung': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/barock-aufklaerung.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/klassik-romantik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/klassik-romantik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/realismus-naturalismus': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/realismus-naturalismus.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/expressionismus-exil': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/expressionismus-exil.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/epochen/nachkrieg-gegenwart': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/epochen/nachkrieg-gegenwart.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/hochsprache': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/akademisch/hochsprache.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/assertive': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/akademisch/assertive.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/direktive': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/akademisch/direktive.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/akademisch/deklarative': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/akademisch/deklarative.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/merkmale': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/merkmale.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/einleitung': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/einleitung.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/erzaehltechnik': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/erzaehltechnik.js'),
  '/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/stilmittel-analyse': () => import('../../../pages/projekte/lernzettel/faecher/deutsch/themen/kurzgeschichte/stilmittel-analyse.js'),
};

export const DEUTSCH_TITLE_TRANSLATION = {
  'page.title.lz.deutsch': 'Deutsch — Lernzettel',
  'page.title.lz.deutsch-was-ist-sprache': 'Was ist Sprache?',
  'page.title.lz.deutsch-leistung-funktion': 'Leistung und Funktion von Sprache',
  'page.title.lz.deutsch-sprachvarietaeten': 'Sprachvarietäten',
  'page.title.lz.deutsch-sprachwandel': 'Sprachwandel',
  'page.title.lz.deutsch-epik': 'Epik',
  'page.title.lz.deutsch-dramatik': 'Dramatik',
  'page.title.lz.deutsch-lyrik': 'Lyrik',
  'page.title.lz.deutsch-sachtexte': 'Sachtexte',
  'page.title.lz.deutsch-reden': 'Reden',
  'page.title.lz.deutsch-analyse': 'Analyse',
  'page.title.lz.deutsch-argumentieren': 'Argumentieren',
  'page.title.lz.deutsch-textgebunden': 'Textgebundene Erörterung',
  'page.title.lz.deutsch-dialektisch': 'Dialektische Erörterung',
  'page.title.lz.deutsch-linear': 'Lineare Erörterung',
  'page.title.lz.deutsch-klangfiguren': 'Klangfiguren',
  'page.title.lz.deutsch-wortfiguren': 'Wortfiguren',
  'page.title.lz.deutsch-satzfiguren': 'Satzfiguren',
  'page.title.lz.deutsch-ironie': 'Ironie',
  'page.title.lz.deutsch-analyse-methodik': 'Analyse‑Methodik',
  'page.title.lz.deutsch-mittelalter': 'Mittelalter',
  'page.title.lz.deutsch-barock-aufklaerung': 'Barock und Aufklärung',
  'page.title.lz.deutsch-klassik-romantik': 'Klassik und Romantik',
  'page.title.lz.deutsch-realismus-naturalismus': 'Realismus und Naturalismus',
  'page.title.lz.deutsch-expressionismus-exil': 'Expressionismus und Exil',
  'page.title.lz.deutsch-nachkrieg-gegenwart': 'Nachkrieg und Gegenwart',
  'page.title.lz.deutsch-hochsprache': 'Hochsprache',
  'page.title.lz.deutsch-assertive': 'Assertive Sprechakte',
  'page.title.lz.deutsch-direktive': 'Direktive Sprechakte',
  'page.title.lz.deutsch-deklarative': 'Deklarative Sprechakte',
  'page.title.lz.deutsch-merkmale': 'Merkmale der Kurzgeschichte',
  'page.title.lz.deutsch-einleitung': 'Einleitung schreiben',
  'page.title.lz.deutsch-erzaehltechnik': 'Erzähltechnik',
  'page.title.lz.deutsch-stilmittel-analyse': 'Stilmittel‑Analyse',
};