// core/routes/faecher/geschichte_routes.js

export const GESCHICHTE_TITLE_KEYS = {
  '/projekte/lernzettel/faecher/geschichte': 'page.title.lz.geschichte',
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/renaissance': 'page.title.lz.geschichte.renaissance',
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/entdeckungen': 'page.title.lz.geschichte.entdeckungen',
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/reformation': 'page.title.lz.geschichte.reformation',
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/dreissigjaehriger-krieg': 'page.title.lz.geschichte.dreissigjaehriger-krieg',
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/england': 'page.title.lz.geschichte.england',
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/deutschland-usa': 'page.title.lz.geschichte.deutschland-usa',
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/soziale-frage': 'page.title.lz.geschichte.soziale-frage',
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/bismarck-sozialgesetze': 'page.title.lz.geschichte.bismarck-sozialgesetze',
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/new-deal': 'page.title.lz.geschichte.new-deal',
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/anfaenge': 'page.title.lz.geschichte.anfaenge',
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/nato-wp-korea': 'page.title.lz.geschichte.nato-wp-korea',
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/kuba-krise': 'page.title.lz.geschichte.kuba-krise',
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/vietnam-prag-entspannung': 'page.title.lz.geschichte.vietnam-prag-entspannung',
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/ende-kalter-krieg': 'page.title.lz.geschichte.ende-kalter-krieg',
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/gedaechtnistheorie': 'page.title.lz.geschichte.gedaechtnistheorie',
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/ns-aufarbeitung': 'page.title.lz.geschichte.ns-aufarbeitung',
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/denkmaeler': 'page.title.lz.geschichte.denkmaeler',
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/historikerstreit': 'page.title.lz.geschichte.historikerstreit',
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/terrorismus': 'page.title.lz.geschichte.terrorismus',
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/eu-krisen': 'page.title.lz.geschichte.eu-krisen',
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/ukraine': 'page.title.lz.geschichte.ukraine',
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/klima-migration': 'page.title.lz.geschichte.klima-migration',
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/demokratie': 'page.title.lz.geschichte.demokratie',
  '/projekte/lernzettel/faecher/geschichte/themen/gedenktage/deutschland': 'page.title.lz.geschichte.gedenktage-de',
  '/projekte/lernzettel/faecher/geschichte/themen/gedenktage/europa-welt': 'page.title.lz.geschichte.gedenktage-welt',
};

export const GESCHICHTE_ROUTES = {
  '/projekte/lernzettel/faecher/geschichte': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/geschichte.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/renaissance': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/renaissance.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/entdeckungen': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/entdeckungen.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/reformation': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/reformation.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/dreissigjaehriger-krieg': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/epochenschwelle/dreissigjaehriger-krieg.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/england': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/england.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/deutschland-usa': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/deutschland-usa.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/soziale-frage': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/soziale-frage.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/bismarck-sozialgesetze': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/bismarck-sozialgesetze.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/new-deal': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/industrialisierung/new-deal.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/anfaenge': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/anfaenge.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/nato-wp-korea': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/nato-wp-korea.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/kuba-krise': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/kuba-krise.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/vietnam-prag-entspannung': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/vietnam-prag-entspannung.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/ende-kalter-krieg': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/kalter-krieg/ende-kalter-krieg.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/gedaechtnistheorie': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/gedaechtnistheorie.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/ns-aufarbeitung': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/ns-aufarbeitung.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/denkmaeler': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/denkmaeler.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/historikerstreit': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/erinnerungskultur/historikerstreit.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/terrorismus': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gegenwart/terrorismus.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/eu-krisen': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gegenwart/eu-krisen.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/ukraine': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gegenwart/ukraine.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/klima-migration': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gegenwart/klima-migration.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gegenwart/demokratie': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gegenwart/demokratie.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gedenktage/deutschland': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gedenktage/deutschland.js'),
  '/projekte/lernzettel/faecher/geschichte/themen/gedenktage/europa-welt': () => import('../../../pages/projekte/lernzettel/faecher/geschichte/themen/gedenktage/europa-welt.js'),
};

export const GESCHICHTE_TITLE_TRANSLATION = {
  'page.title.lz.geschichte': 'Geschichte & GK — Lernzettel',
  'page.title.lz.geschichte.renaissance': 'Renaissance',
  'page.title.lz.geschichte.entdeckungen': 'Entdeckungen',
  'page.title.lz.geschichte.reformation': 'Reformation',
  'page.title.lz.geschichte.dreissigjaehriger-krieg': 'Dreißigjähriger Krieg',
  'page.title.lz.geschichte.england': 'England',
  'page.title.lz.geschichte.deutschland-usa': 'Deutschland und USA',
  'page.title.lz.geschichte.soziale-frage': 'Soziale Frage',
  'page.title.lz.geschichte.bismarck-sozialgesetze': 'Bismarck und Sozialgesetze',
  'page.title.lz.geschichte.new-deal': 'New Deal',
  'page.title.lz.geschichte.anfaenge': 'Anfänge des Kalten Krieges',
  'page.title.lz.geschichte.nato-wp-korea': 'NATO, Warschauer Pakt und Koreakrieg',
  'page.title.lz.geschichte.kuba-krise': 'Kubakrise',
  'page.title.lz.geschichte.vietnam-prag-entspannung': 'Vietnamkrieg, Prager Frühling und Entspannung',
  'page.title.lz.geschichte.ende-kalter-krieg': 'Ende des Kalten Krieges',
  'page.title.lz.geschichte.gedaechtnistheorie': 'Gedächtnistheorie',
  'page.title.lz.geschichte.ns-aufarbeitung': 'Aufarbeitung der NS‑Vergangenheit',
  'page.title.lz.geschichte.denkmaeler': 'Denkmäler',
  'page.title.lz.geschichte.historikerstreit': 'Historikerstreit',
  'page.title.lz.geschichte.terrorismus': 'Terrorismus',
  'page.title.lz.geschichte.eu-krisen': 'EU‑Krisen',
  'page.title.lz.geschichte.ukraine': 'Ukraine',
  'page.title.lz.geschichte.klima-migration': 'Klima und Migration',
  'page.title.lz.geschichte.demokratie': 'Demokratie',
  'page.title.lz.geschichte.gedenktage-de': 'Gedenktage in Deutschland',
  'page.title.lz.geschichte.gedenktage-welt': 'Gedenktage weltweit',
};