// core/routes/faecher/spanisch_routes.js

export const SPANISCH_TITLE_KEYS = {
  '/projekte/lernzettel/faecher/spanisch': 'page.title.lz.spanisch',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/zeitformen': 'page.title.lz.zeitformen',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/ser-estar': 'page.title.lz.ser-estar',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/subjuntivo': 'page.title.lz.subjuntivo',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/indirekte-rede': 'page.title.lz.indirekte-rede',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/objektpronomen': 'page.title.lz.objektpronomen',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/si-saetze': 'page.title.lz.si-saetze',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/imperativo': 'page.title.lz.imperativo',
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/relativsaetze': 'page.title.lz.relativsaetze',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/grundwortschatz': 'page.title.lz.wortschatz.grundwortschatz',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/gesellschaft-politik': 'page.title.lz.wortschatz.gesellschaft-politik',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/umwelt': 'page.title.lz.wortschatz.umwelt',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/identitaet-migration': 'page.title.lz.wortschatz.identitaet-migration',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/technologie': 'page.title.lz.wortschatz.technologie',
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/konnektoren': 'page.title.lz.wortschatz.konnektoren',
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-geschichte': 'page.title.lz.spanien-geschichte',
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-kultur': 'page.title.lz.spanien-kultur',
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/lateinamerika': 'page.title.lz.lateinamerika',
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/gesellschaft-lateinamerika': 'page.title.lz.gesellschaft-lateinamerika',
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/literatur-kunst': 'page.title.lz.literatur-kunst',
};

export const SPANISCH_ROUTES = {
  '/projekte/lernzettel/faecher/spanisch': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/spanisch.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/zeitformen': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/zeitformen.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/ser-estar': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/ser-estar.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/subjuntivo': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/subjuntivo.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/indirekte-rede': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/indirekte-rede.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/objektpronomen': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/objektpronomen.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/si-saetze': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/si-saetze.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/imperativo': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/imperativo.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/grammatik/relativsaetze': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/grammatik/relativsaetze.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/grundwortschatz': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/grundwortschatz.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/gesellschaft-politik': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/gesellschaft-politik.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/umwelt': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/umwelt.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/identitaet-migration': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/identitaet-migration.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/technologie': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/technologie.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/wortschatz/konnektoren': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/wortschatz/konnektoren.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-geschichte': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-geschichte.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-kultur': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/landeskunde/spanien-kultur.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/lateinamerika': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/landeskunde/lateinamerika.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/gesellschaft-lateinamerika': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/landeskunde/gesellschaft-lateinamerika.js'),
  '/projekte/lernzettel/faecher/spanisch/themen/landeskunde/literatur-kunst': () => import('../../../pages/projekte/lernzettel/faecher/spanisch/themen/landeskunde/literatur-kunst.js'),
};

export const SPANISCH_TITLE_TRANSLATION = {
  'page.title.lz.spanisch': 'Spanisch — Lernzettel',
  'page.title.lz.zeitformen': 'Zeitformen — Lernzettel',
  'page.title.lz.ser-estar': 'Ser y estar — Lernzettel',
  'page.title.lz.subjuntivo': 'Subjuntivo — Lernzettel',
  'page.title.lz.indirekte-rede': 'Indirekte Rede — Lernzettel',
  'page.title.lz.objektpronomen': 'Objektpronomen — Lernzettel',
  'page.title.lz.si-saetze': 'Si‑Sätze — Lernzettel',
  'page.title.lz.imperativo': 'Imperativo — Lernzettel',
  'page.title.lz.relativsaetze': 'Relativsätze — Lernzettel',
  'page.title.lz.wortschatz.grundwortschatz': 'Grundwortschatz — Lernzettel',
  'page.title.lz.wortschatz.gesellschaft-politik': 'Gesellschaft & Politik — Lernzettel',
  'page.title.lz.wortschatz.umwelt': 'Umwelt — Lernzettel',
  'page.title.lz.wortschatz.identitaet-migration': 'Identität & Migration — Lernzettel',
  'page.title.lz.wortschatz.technologie': 'Technologie — Lernzettel',
  'page.title.lz.wortschatz.konnektoren': 'Konnektoren — Lernzettel',
  'page.title.lz.spanien-geschichte': 'Spanien — Geschichte',
  'page.title.lz.spanien-kultur': 'Spanien — Kultur',
  'page.title.lz.lateinamerika': 'Lateinamerika — Gesellschaft',
  'page.title.lz.gesellschaft-lateinamerika': 'Gesellschaft in Lateinamerika',
  'page.title.lz.literatur-kunst': 'Literatur & Kunst in der spanischsprachigen Welt',
};