// core/routes/faecher/sport_routes.js

export const SPORT_TITLE_KEYS = {
  '/projekte/lernzettel/faecher/sport': 'page.title.lz.sport',
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/herz-kreislauf': 'page.title.lz.sport.herz-kreislauf',
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/passiver-bewegungsapparat': 'page.title.lz.sport.passiver-bew',
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/aktiver-bewegungsapparat': 'page.title.lz.sport.aktiver-bew',
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/energiebereitstellung': 'page.title.lz.sport.energie',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/grundlagen': 'page.title.lz.sport.tl-grundlagen',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/ausdauer': 'page.title.lz.sport.tl-ausdauer',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/kraft': 'page.title.lz.sport.tl-kraft',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/schnelligkeit': 'page.title.lz.sport.tl-schnelligkeit',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/beweglichkeit': 'page.title.lz.sport.tl-beweglichkeit',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/koordination': 'page.title.lz.sport.tl-koordination',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/technik': 'page.title.lz.sport.tl-technik',
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/lerntheorie': 'page.title.lz.sport.tl-lerntheorie',
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/grundlagen': 'page.title.lz.sport.bl-grundlagen',
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/physik': 'page.title.lz.sport.bl-physik',
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/kraft-zeit-diagramme': 'page.title.lz.sport.bl-kzd',
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/biomechanik': 'page.title.lz.sport.bl-biomechanik',
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/phasenmodelle': 'page.title.lz.sport.bl-phasenmodelle',
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/gesundheitsbegriff': 'page.title.lz.sport.sg-gesundheit',
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/verletzungen': 'page.title.lz.sport.sg-verletzungen',
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/aufwaermen': 'page.title.lz.sport.sg-aufwaermen',
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/ernaehrung': 'page.title.lz.sport.sg-ernaehrung',
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/doping': 'page.title.lz.sport.sg-doping',
  '/projekte/lernzettel/faecher/sport/themen/psychologie/motivation': 'page.title.lz.sport.psy-motivation',
  '/projekte/lernzettel/faecher/sport/themen/psychologie/emotionen': 'page.title.lz.sport.psy-emotionen',
  '/projekte/lernzettel/faecher/sport/themen/psychologie/regeln': 'page.title.lz.sport.psy-regeln',
};

export const SPORT_ROUTES = {
  '/projekte/lernzettel/faecher/sport': () => import('../../../pages/projekte/lernzettel/faecher/sport/sport.js'),
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/herz-kreislauf': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/sportbiologie/herz-kreislauf.js'),
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/passiver-bewegungsapparat': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/sportbiologie/passiver-bewegungsapparat.js'),
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/aktiver-bewegungsapparat': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/sportbiologie/aktiver-bewegungsapparat.js'),
  '/projekte/lernzettel/faecher/sport/themen/sportbiologie/energiebereitstellung': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/sportbiologie/energiebereitstellung.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/grundlagen': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/grundlagen.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/ausdauer': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/ausdauer.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/kraft': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/kraft.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/schnelligkeit': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/schnelligkeit.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/beweglichkeit': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/beweglichkeit.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/koordination': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/koordination.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/technik': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/technik.js'),
  '/projekte/lernzettel/faecher/sport/themen/trainingslehre/lerntheorie': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/trainingslehre/lerntheorie.js'),
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/grundlagen': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/bewegungslehre/grundlagen.js'),
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/physik': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/bewegungslehre/physik.js'),
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/kraft-zeit-diagramme': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/bewegungslehre/kraft-zeit-diagramme.js'),
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/biomechanik': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/bewegungslehre/biomechanik.js'),
  '/projekte/lernzettel/faecher/sport/themen/bewegungslehre/phasenmodelle': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/bewegungslehre/phasenmodelle.js'),
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/gesundheitsbegriff': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/gesundheit/gesundheitsbegriff.js'),
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/verletzungen': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/gesundheit/verletzungen.js'),
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/aufwaermen': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/gesundheit/aufwaermen.js'),
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/ernaehrung': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/gesundheit/ernaehrung.js'),
  '/projekte/lernzettel/faecher/sport/themen/gesundheit/doping': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/gesundheit/doping.js'),
  '/projekte/lernzettel/faecher/sport/themen/psychologie/motivation': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/psychologie/motivation.js'),
  '/projekte/lernzettel/faecher/sport/themen/psychologie/emotionen': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/psychologie/emotionen.js'),
  '/projekte/lernzettel/faecher/sport/themen/psychologie/regeln': () => import('../../../pages/projekte/lernzettel/faecher/sport/themen/psychologie/regeln.js'),
};

export const SPORT_TITLE_TRANSLATION = {
  'page.title.lz.sport': 'Sport — Lernzettel',
  'page.title.lz.sport.herz-kreislauf': 'Herz‑Kreislauf‑System',
  'page.title.lz.sport.passiver-bew': 'Passiver Bewegungsapparat',
  'page.title.lz.sport.aktiver-bew': 'Aktiver Bewegungsapparat',
  'page.title.lz.sport.energie': 'Energiebereitstellung',
  'page.title.lz.sport.tl-grundlagen': 'Grundlagen des Trainings',
  'page.title.lz.sport.tl-ausdauer': 'Ausdauer',
  'page.title.lz.sport.tl-kraft': 'Kraft',
  'page.title.lz.sport.tl-schnelligkeit': 'Schnelligkeit',
  'page.title.lz.sport.tl-beweglichkeit': 'Beweglichkeit',
  'page.title.lz.sport.tl-koordination': 'Koordination',
  'page.title.lz.sport.tl-technik': 'Technik & Taktik',
  'page.title.lz.sport.tl-lerntheorie': 'Lerntheorie & Spielvermittlung',
  'page.title.lz.sport.bl-grundlagen': 'Grundlagen der Bewegungslehre',
  'page.title.lz.sport.bl-physik': 'Physikalische Gesetzmäßigkeiten',
  'page.title.lz.sport.bl-kzd': 'Kraft‑Zeit‑Diagramme',
  'page.title.lz.sport.bl-biomechanik': 'Biomechanische Prinzipien',
  'page.title.lz.sport.bl-phasenmodelle': 'Phasenmodelle',
  'page.title.lz.sport.sg-gesundheit': 'Gesundheitsbegriff',
  'page.title.lz.sport.sg-verletzungen': 'Verletzungen im Sport',
  'page.title.lz.sport.sg-aufwaermen': 'Auf‑ und Abwärmen',
  'page.title.lz.sport.sg-ernaehrung': 'Ernährung & Sport',
  'page.title.lz.sport.sg-doping': 'Doping',
  'page.title.lz.sport.psy-motivation': 'Motive und Motivation',
  'page.title.lz.sport.psy-emotionen': 'Emotionen, Stress & Aggression',
  'page.title.lz.sport.psy-regeln': 'Regeln im Sport',
};