// pages/projekte/lernzettel/eigenes/psychologie/js/translation/languages/en.js

const en = {
  /* ══════════════════════════════════════════════════════════
     HERO
     ══════════════════════════════════════════════════════════ */
  'psy.eyebrow':     'Compendium · Psychology',
  'psy.headline.1':  'Understanding Psychology',
  'psy.headline.2':  'From Theory to the Art of Living.',
  'psy.hero.desc':   'From depth psychology to neuroscience — the key perspectives of psychology, how they connect, and what they mean for everyday life and personal development.',

  'psy.tab.tiefenpsychologie': 'Depth Psychology',
  'psy.tab.behaviorismus':     'Behaviorism',
  'psy.tab.kognitive':         'Cognitive Psych.',
  'psy.tab.humanistische':     'Humanistic Psych.',
  'psy.tab.neurowissenschaft': 'Neuroscience',
  'psy.tab.sozialpsychologie': 'Social Psychology',
  'psy.tab.prokrastination':   'Decision Matrix',

  'psy.footer.extra.title':     'Psychology & Further Reading',
  'psy.footer.extra.back':      'Back to Overview',
  'psy.footer.extra.portfolio': 'Portfolio',

  /* ══════════════════════════════════════════════════════════
     1 · DEPTH PSYCHOLOGY
     ══════════════════════════════════════════════════════════ */

  'psy.tiefenpsychologie.quote':        'The unconscious is the true psychical reality; in its innermost nature it is as much unknown to us as the reality of the external world.',
  'psy.tiefenpsychologie.quote.author': 'Sigmund Freud — The Interpretation of Dreams, 1900',
  'psy.tiefenpsychologie.title':        'Depth Psychology',
  'psy.tiefenpsychologie.intro':        'Depth psychology explores unconscious mental processes and their effects on experience, behavior, and mental health. Founded by Sigmund Freud and further developed by C.G. Jung, Alfred Adler, and object relations theory, it remains one of the most influential schools in clinical psychology and cultural studies.',

  'psy.tiefenpsychologie.sec0.title': 'The Structural Model of the Psyche: Id, Ego and Superego',
  'psy.tiefenpsychologie.sec0.text':  'In his second topography (1923), Freud divided the psyche into three dynamically interacting agencies.\n\nThe Id represents the reservoir of drive energy — libido and destrudo — and operates on the pleasure principle: immediate need satisfaction without regard for reality or morality. It is entirely unconscious and constitutes the phylogenetically oldest layer of personality.\n\nThe Ego develops from the Id through contact with the external world and operates on the reality principle. It mediates between the drive demands of the Id, the moral imperatives of the Superego, and the requirements of reality. Freud compared the Ego to a rider who must guide the superior strength of the horse (Id).\n\nThe Superego arises through internalization of parental and societal norms, particularly during the resolution of the Oedipus complex. It encompasses the conscience (prohibitions, guilt) and the ego-ideal (role models, standards of value). An excessively strict Superego produces neurotic guilt; an underdeveloped one leads to antisocial behavior.\n\nPsychic conflicts arise inevitably since the three agencies make incompatible demands. The Ego must continuously mediate these conflicts — Freud therefore called it "a servant of three masters."',

  'psy.tiefenpsychologie.sec1.title': 'Defense Mechanisms: The Unconscious Self-Regulation',
  'psy.tiefenpsychologie.sec1.text':  'Anna Freud systematized in "The Ego and the Mechanisms of Defence" (1936) the strategies by which the Ego reduces unbearable anxiety. They operate unconsciously and distort reality to varying degrees.\n\nRepression constitutes the primary defense mechanism: threatening drive impulses, memories, or affects are actively prevented from becoming conscious. Repressed content is not deleted — it manifests in parapraxes, dreams, and symptoms.\n\nProjection externalizes one\'s own unacceptable impulses: one\'s own aggression is experienced as hostility from the environment; one\'s own sexual wishes are attributed to others. Clinically, projection appears in paranoid personality disorders.\n\nReaction formation reverses the forbidden impulse into its opposite: hatred becomes excessive friendliness, sexual desires become puritanical rigidity. The behavior often appears rigid and exaggerated.\n\nSublimation is considered the "most mature" defense: drive energy is redirected into socially acceptable channels — aggression into athletic competition, sexual energy into artistic creation.\n\nAdditional mechanisms include rationalization (retrospective pseudo-justification), regression (reversion to earlier developmental stages), displacement (affect is transferred to a substitute object), and intellectualization (emotional distancing through abstract reflection).\n\nDefense is fundamentally adaptive — it becomes pathological only when employed rigidly, excessively, and in reality-distorting ways.',

  'psy.tiefenpsychologie.sec2.title': 'C.G. Jung: Analytical Psychology, Archetypes and Individuation',
  'psy.tiefenpsychologie.sec2.text':  'Carl Gustav Jung (1875–1961) expanded the Freudian model to include a transpersonal dimension. His central concept is the collective unconscious — a psychic depth layer not derived from individual experience but containing species-specific experiential patterns of human history.\n\nArchetypes are the structural elements of the collective unconscious. They manifest in myths, dreams, religious symbols, and cross-cultural motifs. The most important include:\n\n— The Shadow: repressed and negatively evaluated personality aspects. Shadow integration is the first step toward individuation. "One does not become enlightened by imagining figures of light, but by making the darkness conscious" (Jung).\n\n— Anima and Animus: the unconscious contrasexual principle — the Anima as the feminine element in men, the Animus as the masculine element in women. Their projection shapes partner selection and relationship quality.\n\n— The Self: the archetype of wholeness and the goal of the individuation process. It unifies conscious and unconscious aspects of personality.\n\nIndividuation describes the lifelong process of becoming oneself: the gradual integration of Shadow, Anima/Animus, and further archetypes into a conscious, holistic personality. Jung\'s psychology influenced not only therapy but also mythology (Joseph Campbell), literary studies, and philosophy of religion.',

  'psy.tiefenpsychologie.sec3.title': 'Adler: Individual Psychology, Social Interest and Lifestyle',
  'psy.tiefenpsychologie.sec3.text':  'Alfred Adler (1870–1937) founded Individual Psychology as an independent school that views humans as an indivisible unity (Lat. individuum = the indivisible) within their social context.\n\nInferiority feeling and compensation form Adler\'s central motivation theory. Every person experiences organic, intellectual, or social inferiority as a child. This basic feeling generates a striving for overcoming — compensation. Healthy compensation leads to achievement and creativity; pathological overcompensation manifests as power-seeking, narcissism, or withdrawal.\n\nThe inferiority complex arises when the natural inferiority feeling is not constructively processed. It manifests in avoidance behavior, hypersensitivity to criticism, or compensatory grandiosity.\n\nSocial interest is Adler\'s ethical and therapeutic core concept. He defined mental health as the ability to cooperatively address the three life tasks — work, love, and community. Neurosis he interpreted as "failure before life tasks" due to insufficient social interest.\n\nThe lifestyle forms during the first six years of life and encompasses the individual beliefs, goals, and strategies with which a person seeks to overcome their subjectively experienced inferiority. Adler\'s influence on educational counseling, systemic therapy, and cognitive behavioral therapy is considerable — Aaron T. Beck called him "the great-grandfather of cognitive therapy."',

  /* ══════════════════════════════════════════════════════════
     2 · BEHAVIORISM
     ══════════════════════════════════════════════════════════ */

  'psy.behaviorismus.quote':        'Give me a dozen healthy infants, well-formed, and my own specified world to bring them up in and I\'ll guarantee to take any one at random and train him to become any type of specialist — doctor, lawyer, artist, merchant-chief, and yes, even beggar-man and thief.',
  'psy.behaviorismus.quote.author': 'John B. Watson — Behaviorism, 1924',
  'psy.behaviorismus.title':        'Behaviorism',
  'psy.behaviorismus.intro':        'Behaviorism established psychology as an objective natural science by restricting itself to observable and measurable behavior. Internal states such as consciousness, feelings, or motives were considered scientifically inaccessible — only the functional relationship between environmental stimuli (Stimulus) and behavioral responses (Response) was relevant.',

  'psy.behaviorismus.sec0.title': 'Classical Conditioning: Pavlov, Watson and the Laws of Association',
  'psy.behaviorismus.sec0.text':  'Ivan Petrovich Pavlov (1849–1936) discovered a fundamental learning principle during his digestive experiments with dogs: when an originally neutral stimulus (NS) is repeatedly presented together with an unconditioned stimulus (UCS), the neutral stimulus acquires the ability to elicit a conditioned response (CR) — it becomes a conditioned stimulus (CS).\n\nAcquisition follows a negatively accelerated learning curve: associative strength increases rapidly at first, then ever more slowly. Rescorla and Wagner (1972) demonstrated that not mere contiguity (temporal coincidence) is decisive, but contingency — the informational value of the CS regarding the occurrence of the UCS.\n\nExtinction occurs when the CS is repeatedly presented without the UCS. The conditioned response disappears but is not erased: spontaneous recovery proves that the original association remains latently preserved.\n\nStimulus generalization and stimulus discrimination are complementary processes: generalization causes stimuli similar to the CS to also elicit the CR; discrimination allows differentiation between the relevant CS and irrelevant stimuli.\n\nJohn B. Watson demonstrated in the ethically controversial "Little Albert" experiment (1920) that fear responses can be classically conditioned in humans — a foundation for understanding phobias and anxiety disorders.',

  'psy.behaviorismus.sec1.title': 'Operant Conditioning: Thorndike, Skinner and Consequence Control',
  'psy.behaviorismus.sec1.text':  'Edward Lee Thorndike (1874–1949) formulated the "Law of Effect": behaviors that lead to a satisfying state are strengthened; those that lead to an unpleasant state are weakened.\n\nB.F. Skinner (1904–1990) systematized this principle into operant conditioning. Behavior is controlled by its consequences:\n\n— Positive reinforcement: a pleasant stimulus follows the behavior → behavioral frequency increases (praise after good performance).\n— Negative reinforcement: an aversive stimulus is removed by the behavior → behavioral frequency increases (headache tablet ends pain → more frequent tablet use).\n— Positive punishment (Type I): an aversive stimulus follows the behavior → behavioral frequency decreases.\n— Negative punishment (Type II): a pleasant stimulus is withdrawn → behavioral frequency decreases.\n\nReinforcement schedules determine extinction resistance: continuous reinforcement produces fast learning but low extinction resistance. Intermittent reinforcement (variable ratio or interval schedules) produces high response rates and extreme extinction resistance — the principle behind gambling addiction and social media algorithms.\n\nSkinner\'s radical behaviorism did not deny mental explanations but considered them "private events" subject to the same laws as public behavior.',

  'psy.behaviorismus.sec2.title': 'Social-Cognitive Learning Theory: Bandura and Overcoming the S-R Paradigm',
  'psy.behaviorismus.sec2.text':  'Albert Bandura (1925–2021) broke through the boundaries of classical behaviorism with his social-cognitive learning theory by introducing cognitive variables as mediators between stimulus and response.\n\nThe Bobo Doll Experiment (1961) demonstrated observational learning: children who observed an aggressive model showed significantly more aggressive behavior than control groups — without direct reinforcement. Bandura identified four sub-processes: attention, retention, motor reproduction, and motivation.\n\nReciprocal determinism postulates that behavior, person (cognitive schemas, beliefs), and environment mutually influence each other — in contrast to the unidirectional environmental determination of radical behaviorism.\n\nSelf-efficacy is Bandura\'s most influential concept: the subjective belief in one\'s ability to successfully perform a specific action. Four sources feed it: mastery experiences (strongest source), vicarious experience (observing models), verbal persuasion (encouragement), and physiological/affective states. Meta-analyses confirm that self-efficacy is one of the strongest predictors of performance, health behavior, and stress management.',

  'psy.behaviorismus.sec3.title': 'Clinical Application: Evidence-Based Behavioral Therapy',
  'psy.behaviorismus.sec3.text':  'Behavioral therapy translates learning theory principles into clinical interventions and is among the most empirically validated forms of therapy.\n\nSystematic desensitization (Wolpe, 1958): treatment of anxiety disorders through gradual exposure to anxiety-provoking stimuli with simultaneous muscle relaxation. The principle of reciprocal inhibition states that anxiety and relaxation cannot occur simultaneously.\n\nExposure with response prevention (ERP): gold standard for OCD and specific phobias. The patient is exposed to the feared stimulus without performing avoidance or neutralization behavior — the anxiety response habituates.\n\nContingency management: systematic use of reinforcement in institutional settings (Token Economy). Effective for substance dependence, ADHD, and developmental disorders.\n\nBehavioral activation: for depression, pleasant and mastery-oriented activities are systematically increased — based on the insight that depressive inactivity maintains the vicious cycle of reduced reinforcement and declining mood. Meta-analyses show effect sizes comparable to antidepressants.',

  /* ══════════════════════════════════════════════════════════
     3 · COGNITIVE PSYCHOLOGY
     ══════════════════════════════════════════════════════════ */

  'psy.kognitive.quote':        'It is not things themselves that disturb us, but our judgments and opinions about things.',
  'psy.kognitive.quote.author': 'Epictetus — Enchiridion, ca. 125 AD (foundational idea of cognitive therapy)',
  'psy.kognitive.title':        'Cognitive Psychology',
  'psy.kognitive.intro':        'Cognitive psychology examines the mental processes that mediate between stimulus input and behavioral response: perception, attention, memory, language, problem-solving, and judgment formation. It models humans as information-processing systems and forms the theoretical foundation of cognitive behavioral therapy.',

  'psy.kognitive.sec0.title': 'Cognitive Biases and Heuristics: The Architecture of Flawed Thinking',
  'psy.kognitive.sec0.text':  'The research program of Amos Tversky and Daniel Kahneman (from 1971) revolutionized the understanding of human judgment. They identified systematic deviations from rational norms — cognitive biases resulting from the use of fast but error-prone heuristics.\n\nAvailability heuristic: the probability of an event is judged by how easily examples can be retrieved from memory. Media-overrepresented events (plane crashes) are overestimated; statistically more frequent events (car accidents) are underestimated.\n\nAnchoring effect: an initial reference value (anchor) influences all subsequent judgments, even when the anchor is obviously irrelevant. In negotiations, the first offer determines the framework for all subsequent bids.\n\nConfirmation bias: the tendency to search for, interpret, and remember information that confirms existing beliefs — while contradictory information is ignored or discredited. Wason (1960) demonstrated this with the 2-4-6 task.\n\nDunning-Kruger effect: individuals with low competence systematically overestimate their abilities, while highly competent individuals underestimate their performance — because competence and the ability to assess that competence correlate.\n\nThese biases are not defects but evolutionarily adaptive shortcuts that usually work under time pressure and uncertainty — but produce systematic errors in complex, modern decision environments.',

  'psy.kognitive.sec1.title': 'Memory Systems: From Sensory Register to Long-Term Storage',
  'psy.kognitive.sec1.text':  'The multi-store model of Atkinson and Shiffrin (1968) distinguishes three sequential stages of information processing.\n\nThe sensory register (iconic/echoic) stores unprocessed sensory impressions for fractions of a second (iconic ~250ms, echoic ~3s). Sperling\'s partial report procedure (1960) proved that capacity is far greater than what can be consciously reported.\n\nShort-term memory (STM) / working memory holds actively processed information. Miller\'s "Magical Number Seven" (1956) described the capacity limitation to 7±2 units. Baddeley and Hitch (1974) expanded the concept into the working memory model with phonological loop, visuospatial sketchpad, and central executive.\n\nLong-term memory (LTM) has practically unlimited capacity. Tulving (1972) distinguished episodic memory (personal experiences), semantic memory (world knowledge), and procedural memory (skills). Consolidation — the transfer from STM to LTM — is controlled by the hippocampus and enhanced by sleep, elaboration, and emotional significance.\n\nThe testing effect (Roediger & Karpicke, 2006) shows: active retrieval is more effective than repeated reading. The spacing effect (distributed practice) and interleaving (alternating practice of different task types) optimize long-term retention — evidence-based strategies that significantly outperform traditional study methods.',

  'psy.kognitive.sec2.title': 'Cognitive Therapy: Beck, Ellis and Therapeutic Restructuring',
  'psy.kognitive.sec2.text':  'Aaron T. Beck (1921–2021) developed cognitive therapy (CT) from the clinical observation that depressive patients show characteristic thinking errors.\n\nThe cognitive model posits three levels of dysfunctional cognition:\n\n1. Automatic thoughts: spontaneous, fleeting evaluations that often go unnoticed but directly control emotions and behavior (e.g., "I always fail").\n\n2. Cognitive distortions: systematic thinking errors such as overgeneralization (one negative event is interpreted as a general pattern), dichotomous thinking (black-and-white thinking), catastrophizing (expecting the worst outcome), and personalization (assuming responsibility for external events).\n\n3. Core beliefs and schemas: deeply rooted beliefs about self, others, and the world that arise in childhood and systematically bias information processing.\n\nBeck\'s cognitive triad of depression describes negative schemas regarding the self ("I am worthless"), the world ("The world is hostile"), and the future ("It will never get better").\n\nAlbert Ellis developed the Rational Emotive Behavior Therapy (REBT) in parallel with the ABC model: not the activating event (A) causes the emotional consequence (C), but the irrational belief (B). Therapeutically, irrational beliefs are identified, disputed, and replaced with rational alternatives.\n\nCognitive behavioral therapy (CBT) — the integration of cognitive and behavioral approaches — is the most extensively evidence-based psychotherapy form with demonstrated efficacy for depression, anxiety disorders, PTSD, eating disorders, and chronic pain.',

  'psy.kognitive.sec3.title': 'Dual-Process Theory: Two Systems of Thinking',
  'psy.kognitive.sec3.text':  'Daniel Kahneman\'s Dual-Process Theory (summarized in "Thinking, Fast and Slow," 2011) distinguishes two fundamental processing modes.\n\nSystem 1 operates fast, automatically, effortlessly, and unconsciously. It processes faces, recognizes emotions, completes sentences, and controls everyday actions. It works in parallel, uses heuristics, and is susceptible to systematic biases. It is the evolutionarily older system.\n\nSystem 2 is slow, controlled, effortful, and conscious. It is activated for complex calculations, logical reasoning, self-control, and checking System 1 judgments. It works serially and has limited capacity — it tires easily (ego depletion).\n\nKahneman\'s central insight: most cognitive biases arise because System 1 takes over problems that actually require System 2 — and System 2 is too "lazy" or too exhausted to intervene.\n\nThe theory has far-reaching implications for nudging (Thaler & Sunstein), behavioral economics, medical diagnostics, and risk communication. It explains why statistical thinking is counterintuitive, why experts systematically err, and why "more information" does not automatically lead to better decisions.',

  /* ══════════════════════════════════════════════════════════
     4 · HUMANISTIC PSYCHOLOGY
     ══════════════════════════════════════════════════════════ */

  'psy.humanistische.quote':        'What a man can be, he must be. He must be true to his own nature.',
  'psy.humanistische.quote.author': 'Abraham Maslow — Motivation and Personality, 1954',
  'psy.humanistische.title':        'Humanistic Psychology',
  'psy.humanistische.intro':        'Humanistic psychology emerged in the 1960s as the "third force" alongside psychoanalysis and behaviorism. It emphasizes unique human capacities for self-reflection, free choice, and meaning-making, placing positive growth potential at the center — rather than pathology and deficits.',

  'psy.humanistische.sec0.title': 'Maslow\'s Hierarchy of Needs and the Concept of Self-Actualization',
  'psy.humanistische.sec0.text':  'Abraham Maslow (1908–1970) arranged human needs in a hierarchical structure commonly visualized as a pyramid:\n\n1. Physiological needs: food, water, sleep, homeostasis — the biological foundation of existence.\n2. Safety needs: physical security, financial stability, health, order, and predictability.\n3. Social needs (belonging and love): friendship, intimacy, family bonds, social integration.\n4. Esteem needs: recognition, competence experience, self-respect, status — Maslow distinguished between external esteem and self-esteem.\n5. Self-actualization: the actualization of one\'s own potential — "becoming everything one is capable of becoming."\n\nMaslow studied exemplary personalities (Lincoln, Einstein, Eleanor Roosevelt) and identified traits of self-actualized individuals: problem-centering rather than self-centering, autonomy, peak experiences, democratic value orientation, and "social interest" (in Adler\'s sense).\n\nLater criticism concerns the strict hierarchy (not consistently confirmed empirically), the cultural shaping of the need order, and the methodological basis. Nevertheless, Maslow\'s model remains one of the most influential concepts in psychology, education, and management.',

  'psy.humanistische.sec1.title': 'Rogers: Person-Centered Therapy and the Concept of Congruence',
  'psy.humanistische.sec1.text':  'Carl R. Rogers (1902–1987) developed person-centered therapy (client-centered therapy), which rests on three necessary and sufficient conditions for therapeutic change:\n\n1. Empathy (empathic understanding): the therapist enters the client\'s inner experiential world and communicates this understanding. Empathy is not sympathy but a precise grasping of the other\'s subjective frame of reference.\n\n2. Congruence (genuineness): the therapist is authentic in the relationship — experience, awareness, and communication are aligned. No professional facade.\n\n3. Unconditional positive regard: the therapist accepts the client as a person without conditions — regardless of behavior, feelings, or beliefs.\n\nRogers postulated the actualizing tendency as the single motivational ground principle: every organism naturally strives toward growth, development, and autonomy. Psychological disorders arise through incongruence — the discrepancy between the self-concept (self-image) and actual organismic experience.\n\nConditions of worth, internalized in childhood, cause people to deny or distort parts of their experience. Therapy creates through the three core conditions a space in which the client can perceive and accept themselves without distortion.',

  'psy.humanistische.sec2.title': 'Positive Psychology: Seligman, PERMA and the Science of Flourishing',
  'psy.humanistische.sec2.text':  'Martin Seligman (*1942) founded Positive Psychology in 1998 as APA president as a scientific research program. It examines not what makes people ill but what makes them flourish — well-being rather than pathology.\n\nThe PERMA model identifies five empirically measurable pillars of well-being:\n\n— Positive Emotions: joy, gratitude, interest, hope, inspiration — Barbara Fredrickson\'s broaden-and-build theory shows that positive emotions expand the thought-action repertoire and build psychological resources.\n— Engagement: deep absorption in activities (Flow) — complete absorption where action and awareness merge.\n— Relationships: qualitative social bonds as the strongest predictor of life satisfaction — the Harvard Study of Adult Development (since 1938) confirms this over 85 years.\n— Meaning: the feeling of being part of something greater than oneself — connected to Viktor Frankl\'s logotherapy and the "will to meaning."\n— Achievement: performance and competence experience for its own sake — Angela Duckworth\'s research on "grit" (perseverance) as a key factor.\n\nCharacter strengths research (Peterson & Seligman, 2004): the VIA classification identifies 24 universal character strengths (wisdom, courage, humanity, justice, temperance, transcendence). Intervention studies show that conscious deployment of signature strengths increases well-being and reduces depressive symptoms.',

  'psy.humanistische.sec3.title': 'Flow Theory: Csikszentmihalyi and the Psychology of Optimal Experience',
  'psy.humanistische.sec3.text':  'Mihaly Csikszentmihalyi (1934–2021) researched from the 1970s the flow state — the experience of complete absorption in an activity where time sense disappears, self-awareness recedes, and intrinsic motivation peaks.\n\nEight components of flow according to Csikszentmihalyi:\n1. Balance between challenge and skill (challenge-skill balance)\n2. Merging of action and awareness\n3. Clear goals\n4. Immediate feedback\n5. Concentration on the task\n6. Sense of control\n7. Loss of self-reflective consciousness\n8. Altered sense of time\n\nThe flow channel: when demands exceed abilities → anxiety/overwhelm. When abilities exceed demands → boredom/apathy. Flow arises in the dynamic balance — and shifts with growing competence to higher challenges (autotelic personality).\n\nNeuroscientific correlates: during flow, a transient hypofrontality appears — a downregulation of the prefrontal cortex that reduces self-criticism and analytical thinking, enabling fluid, effortless action. Arne Dietrich (2004) described this as the "transient hypofrontality hypothesis."\n\nPractical implication: flow is trainable. The systematic adjustment of challenges to one\'s own skill level — neither too easy nor too hard — produces optimal learning and performance states.',

  /* ══════════════════════════════════════════════════════════
     5 · NEUROSCIENCE
     ══════════════════════════════════════════════════════════ */

  'psy.neurowissenschaft.quote':        'We are our brains — but our brains are more than we believe ourselves to be.',
  'psy.neurowissenschaft.quote.author': 'Dick Swaab — We Are Our Brains, 2010',
  'psy.neurowissenschaft.title':        'Neuroscience',
  'psy.neurowissenschaft.intro':        'Neuroscience investigates how the nervous system produces behavior, cognition, and emotion. It integrates findings from neuroanatomy, neurophysiology, neurochemistry, neuroimaging, and computational neuroscience into a biological understanding of mental processes.',

  'psy.neurowissenschaft.sec0.title': 'Neural Signal Transmission: Action Potentials, Synapses and Neurotransmitters',
  'psy.neurowissenschaft.sec0.text':  'The human brain contains approximately 86 billion neurons (Azevedo et al., 2009) communicating via an estimated 100–500 trillion synapses — the most complex known system in the universe.\n\nElectrical signaling: the action potential is an all-or-nothing signal propagating along the axon. It arises through sequential influx of Na⁺ ions (depolarization) and efflux of K⁺ ions (repolarization) via voltage-gated ion channels. Myelination by oligodendrocytes (CNS) and Schwann cells (PNS) accelerates conduction velocity up to 120 m/s through saltatory conduction.\n\nChemical signaling: at the synapse, the electrical signal is converted into a chemical one. Neurotransmitters are released from presynaptic vesicles into the synaptic cleft and bind to postsynaptic receptors.\n\nKey neurotransmitters and their psychological relevance:\n— Dopamine: reward expectation, motivation, motor control. Dysfunction in addiction (mesolimbic system) and Parkinson\'s (nigrostriatal system). The reward prediction error signal (Schultz, 1997) shows: dopamine codes not reward itself but the deviation of reward from expectation.\n— Serotonin (5-HT): mood regulation, impulse control, sleep-wake regulation. Selective serotonin reuptake inhibitors (SSRIs) are first-line treatment for depression.\n— GABA (γ-aminobutyric acid): main inhibitory neurotransmitter. Benzodiazepines act via GABA-A receptors anxiolytically.\n— Glutamate: main excitatory neurotransmitter. NMDA receptors are essential for long-term potentiation (LTP) — the synaptic mechanism of learning and memory.',

  'psy.neurowissenschaft.sec1.title': 'Neuroplasticity: The Brain as a Self-Remodeling Organ',
  'psy.neurowissenschaft.sec1.text':  'Neuroplasticity — the experience-dependent modification of neural structures and functions — has revolutionized the static image of the adult brain.\n\nSynaptic plasticity: Donald Hebb\'s postulate (1949) — "Neurons that fire together, wire together" — describes the activity-dependent strengthening of synaptic connections (long-term potentiation, LTP). Conversely, unused connections weaken (synaptic pruning, long-term depression LTD). These mechanisms form the neurobiological basis of learning and memory.\n\nStructural plasticity: Maguire et al. (2000) showed that London taxi drivers have an enlarged posterior hippocampus — proportional to years of experience. Musicians show enlarged auditory cortices and finer somatosensory representations of fingers. These studies demonstrate that intensive practice measurably changes brain structure.\n\nAdult neurogenesis: contrary to the old dogma, new neurons are generated throughout life in the hippocampus (dentate gyrus) and subventricular zone. Physical activity, cognitive stimulation, and enriched environments promote neurogenesis; chronic stress, sleep deprivation, and social isolation inhibit it.\n\nClinical relevance: neuroplasticity is the biological basis of all psychotherapy. Cognitive behavioral therapy demonstrably changes activity in the prefrontal cortex and amygdala (Goldapple et al., 2004). Mindfulness meditation thickens the prefrontal cortex and reduces amygdala reactivity (Hölzel et al., 2011).',

  'psy.neurowissenschaft.sec2.title': 'The Emotional Brain: Limbic System, Stress Axis and Affective Regulation',
  'psy.neurowissenschaft.sec2.text':  'The amygdala is the central structure for processing emotional significance, particularly threat and fear. LeDoux (1996) identified two processing pathways:\n\n— The "low road" (thalamo-amygdalar route): fast, crude threat detection — the reason we flinch at a stick-like object before consciously identifying it as a stick.\n— The "high road" (thalamo-cortical-amygdalar route): slow, differentiated analysis — enables context-dependent reappraisal.\n\nThe prefrontal cortex (PFC) — especially the ventromedial and dorsolateral PFC — regulates emotional reactions top-down. It enables cognitive reappraisal, impulse control, and the suppression of inappropriate reactions.\n\nThe HPA axis (hypothalamic-pituitary-adrenal axis): under stress, the hypothalamus activates CRH release → the pituitary releases ACTH → the adrenal cortex produces cortisol. Acute stress mobilizes energy and sharpens attention. Chronic stress, however:\n— Damages hippocampal neurons (Sapolsky, 2004) → memory impairments\n— Enhances amygdala reactivity → increased anxiety readiness\n— Weakens the PFC → reduced self-regulation\n— Suppresses the immune system (psychoneuroimmunology)\n\nThe polyvagal theory (Porges, 2011) describes three hierarchically organized response patterns to threat: social engagement (ventral vagus), fight/flight (sympathetic), and freeze (dorsal vagus).',

  'psy.neurowissenschaft.sec3.title': 'Sleep and Cognitive Performance: Consolidation, Homeostasis and Circadian Rhythms',
  'psy.neurowissenschaft.sec3.text':  'Sleep is an active, highly structured neurobiological process essential for cognitive function, emotional regulation, and physical health.\n\nSleep architecture: a sleep cycle (~90 min) progresses through stages N1 (falling asleep), N2 (light sleep with sleep spindles and K-complexes), N3 (deep sleep/slow-wave sleep), and REM sleep (rapid eye movement). 4–6 cycles are completed per night, with deep sleep dominating the first half and REM the second half.\n\nMemory consolidation: Walker and Stickgold (2004) showed that different sleep phases strengthen different memory systems:\n— Deep sleep (N3): consolidation of declarative (explicit) memories — the hippocampus "replays" day experiences and transfers them to the neocortex (systems consolidation).\n— REM sleep: consolidation of procedural and emotional memories, creative problem-solving, emotional processing.\n\nThe glymphatic system (Nedergaard, 2012): during sleep, the spaces between brain cells expand by 60%, enabling the removal of neurotoxic metabolic products (including beta-amyloid, an Alzheimer\'s marker).\n\nSleep deprivation: Matthew Walker\'s research (Why We Sleep, 2017) documents the consequences:\n— Cognition: one night of 6h sleep reduces cognitive performance by ~30%. After 4 days of 6h sleep, impairment equals 24h total sleep deprivation.\n— Emotional regulation: amygdala reactivity increases by 60% after sleep deprivation (Yoo et al., 2007) — the connection between PFC and amygdala is weakened.\n— Immune system: 4–5h sleep reduces natural killer cell activity by 70%.\n— Learning capacity: sleep before learning prepares the hippocampus for new information uptake; sleep after learning consolidates what was learned.',

  /* ══════════════════════════════════════════════════════════
     6 · SOCIAL PSYCHOLOGY
     ══════════════════════════════════════════════════════════ */

  'psy.sozialpsychologie.quote':        'We don\'t see things as they are — we see them as we are.',
  'psy.sozialpsychologie.quote.author': 'Anaïs Nin — Seduction of the Minotaur, 1961',
  'psy.sozialpsychologie.title':        'Social Psychology',
  'psy.sozialpsychologie.intro':        'Social psychology examines how people\'s thoughts, feelings, and behaviors are influenced by the actual, imagined, or implied presence of others (Allport, 1954). It combines experimental methodology with the analysis of social phenomena.',

  'psy.sozialpsychologie.sec0.title': 'Conformity and Obedience: Asch, Milgram and the Power of the Situation',
  'psy.sozialpsychologie.sec0.text':  'Solomon Asch\'s conformity experiment (1951): participants were asked to compare line lengths — a trivial task. Yet when confederates deliberately gave wrong answers, 75% of participants conformed at least once. Conformity rate varied with group size, unanimity, and anonymity.\n\nAsch distinguished informational social influence (adopting others\' opinions because one believes them correct — especially under ambiguity) and normative social influence (conforming to secure belonging and avoid rejection).\n\nStanley Milgram\'s obedience experiment (1963) is one of the most disturbing findings in social psychology: 65% of participants administered seemingly life-threatening 450-volt electric shocks on the instruction of an authority figure — despite the "learner" (confederate) clearly expressing pain and requesting to stop.\n\nMilgram identified situational factors increasing obedience: proximity to authority, distance from victim, institutional legitimacy, and gradual escalation. His research was conducted after the Eichmann trial and showed: ordinary people can exhibit extraordinarily destructive behavior under specific situational conditions.\n\nPhilip Zimbardo\'s Stanford Prison Experiment (1971) demonstrated how rapidly role assignments can determine behavior. Zimbardo formulated the "Lucifer Effect": not "evil people" produce "evil deeds," but "evil systems" corrupt ordinary people.',

  'psy.sozialpsychologie.sec1.title': 'Groupthink, Social Identity and Intergroup Conflict',
  'psy.sozialpsychologie.sec1.text':  'Irving Janis (1972) coined the term Groupthink: in cohesive groups with strong consensus pressure, decision pathologies arise — illusion of invulnerability, collective rationalization, out-group stereotyping, self-censorship, and illusion of unanimity. Historical examples: Bay of Pigs invasion, Challenger disaster.\n\nPrevention strategies: appointing a "devil\'s advocate," soliciting external expert opinions, anonymous voting, encouraging dissenting views.\n\nHenri Tajfel\'s Social Identity Theory (1979) explains how group membership shapes self-concept and behavior:\n\n1. Social categorization: people classify themselves and others into groups (ingroup/outgroup).\n2. Social identification: group membership becomes part of self-concept — its value affects self-esteem.\n3. Social comparison: groups are compared, with the own group systematically upgraded (ingroup favoritism).\n\nThe minimal group paradigm (Tajfel et al., 1971) showed: even with arbitrary group assignment (e.g., Klee vs. Kandinsky preference), ingroup favoritism occurs — mere categorization suffices.\n\nGordon Allport\'s Contact Hypothesis (1954) posits that prejudice is reduced through intergroup contact under specific conditions: equal status, common goals, institutional support, and cooperation (not competition). Pettigrew and Tropp\'s meta-analysis (2006, 515 studies) robustly confirmed the contact effect.',

  'psy.sozialpsychologie.sec2.title': 'Cognitive Dissonance: Festinger\'s Theory of Inner Contradictions',
  'psy.sozialpsychologie.sec2.text':  'Leon Festinger\'s theory of cognitive dissonance (1957) is among the most influential social psychological theories. Its core assertion: when two cognitions (beliefs, attitudes, knowledge about one\'s own behavior) are inconsistent, an aversive tension state arises — cognitive dissonance — which the person is motivated to reduce.\n\nStrategies for dissonance reduction:\n— Attitude change: adjusting the belief to match behavior (e.g., smoker: "It\'s not really that dangerous").\n— Behavior change: adjusting behavior to match the belief (quitting smoking).\n— Adding consonant cognitions: seeking new information that mitigates the inconsistency.\n— Trivialization: downplaying the importance of the inconsistent cognition.\n\nThe classic forced-compliance experiment (Festinger & Carlsmith, 1959): participants who described a boring task as interesting for only $1 (insufficient external justification) changed their attitude more than those receiving $20. Insufficient external justification creates the highest dissonance.\n\nApplications: post-decisional dissonance (upgrading the chosen, downgrading the rejected alternative), effort justification (harder initiations → higher group evaluation), selective exposure (preferential consumption of attitude-consistent media — "echo chambers").',

  'psy.sozialpsychologie.sec3.title': 'Prosocial Behavior, Bystander Effect and the Psychology of Helping',
  'psy.sozialpsychologie.sec3.text':  'The bystander effect was experimentally investigated by John Darley and Bibb Latané after the murder of Kitty Genovese (1964). Their finding: the more bystanders present at an emergency, the lower the probability that any individual will help.\n\nThree psychological mechanisms explain the effect:\n1. Diffusion of responsibility: "Someone else will help" — perceived personal responsibility decreases with the number of people present.\n2. Pluralistic ignorance: in ambiguous situations, people orient to others\' behavior. When nobody reacts, everyone interprets the situation as harmless — although all are concerned.\n3. Evaluation apprehension: the worry of embarrassing oneself through inappropriate action.\n\nLatané and Darley\'s 5-stage model of helping: (1) notice the situation → (2) interpret as emergency → (3) assume personal responsibility → (4) perceive competence to help → (5) decide to act. The process can abort at each stage.\n\nFactors promoting prosocial behavior: empathy (Batson, 1991: empathically motivated helping is genuine altruism, not egoism reduction), personal norms and self-concept as a "helpful person," perceived similarity with the person in need, good mood (Isen & Levin, 1972: coin in coin slot → more helpfulness), low costs of helping, and clear action options.',

  /* ══════════════════════════════════════════════════════════
     7 · PROCRASTINATION — Decision Matrix
     17 universal areas as dialog-bubbles
     ══════════════════════════════════════════════════════════ */

  'psy.prokr.quote':        'Procrastination is not a time management problem — it is an emotion regulation problem.',
  'psy.prokr.quote.author': 'Timothy Pychyl — Solving the Procrastination Puzzle, 2013',
  'psy.prokr.title':        'Decision Matrix: Overcoming Procrastination',
  'psy.prokr.intro':        'Procrastination is the irrational postponement of actions despite awareness of negative consequences. Research by Pychyl, Steel, and Sirois shows: it is a disorder of emotion regulation — short-term affect is prioritized at the expense of long-term goals. The following matrix confronts 17 central life areas with scientific findings.',

  'psy.prokr.impact': 'Impact',

  'psy.prokr.bildung.label': 'Education',
  'psy.prokr.bildung.q': 'Why is it so hard to make yourself study, even when you know the consequences?',
  'psy.prokr.bildung.a': 'Steel\'s Temporal Motivation Theory (2007) explains: motivation decreases exponentially with the temporal distance of reward (temporal discounting). Exams in weeks feel less motivating than YouTube now. The solution is implementation planning (Gollwitzer, 1999): concrete if-then plans ("When it\'s 3 PM, I open the chemistry textbook") increase implementation probability by 40–60% by removing the decision burden from the moment.',

  'psy.prokr.morgenroutine.label': 'Morning Routine',
  'psy.prokr.morgenroutine.q': 'Does waking up earlier actually help — or is that just a productivity-culture myth?',
  'psy.prokr.morgenroutine.a': 'No myth. Chronobiologically, peak cognitive performance for most people ("lark" chronotype) falls 2–4 hours after waking (Valdez et al., 2012). Sleeping through this phase means losing the most productive segment of the day. Consistency is key: irregular wake times desynchronize the circadian rhythm and reduce sleep quality — an effect Wittmann et al. (2006) described as "social jetlag." Rising 90 minutes earlier with unchanged sleep duration yields ~550 extra hours per year.',

  'psy.prokr.mentale_kompetenz.label': 'Mental Strength',
  'psy.prokr.mentale_kompetenz.q': 'How can you stop being paralyzed by negative thoughts?',
  'psy.prokr.mentale_kompetenz.a': 'Beck\'s cognitive model shows: it\'s not events that cause emotions, but their appraisal (ABC model). Metacognitive therapy (Wells, 2009) goes further: the problem isn\'t the negative thought itself, but the reaction to it — rumination and worry as maladaptive coping strategies. Training in cognitive defusion (ACT) and expressive writing (Pennebaker, 1997) — 15 minutes of journaling about distressing experiences — demonstrably reduces intrusions, lowers cortisol, and improves immune function.',

  'psy.prokr.beziehungen.label': 'Relationships',
  'psy.prokr.beziehungen.q': 'Is maintaining relationships during intense study periods really a good time investment?',
  'psy.prokr.beziehungen.a': 'Unequivocally yes. The Harvard Study of Adult Development (since 1938, Waldinger & Schulz, 2023) — the longest longitudinal study in history — shows: qualitative relationships are the strongest predictor of health, life satisfaction, and cognitive function in old age. Social support buffers stress through HPA axis activity reduction (Cohen & Wills, 1985). What matters is not quantity but quality: one hour of focused attention is more valuable than hours of presence without connection.',

  'psy.prokr.hobbys.label': 'Hobbies & Balance',
  'psy.prokr.hobbys.q': 'Are hobbies a waste of time when you should actually be studying?',
  'psy.prokr.hobbys.a': 'The opposite: strategically deployed hobbies increase learning performance. Physical activity improves executive functions, memory consolidation, and hippocampal neurogenesis (Hillman et al., 2008). The effort-recovery theory (Meijman & Mulder, 1998) shows: recovery requires activities that engage different psychological resources than the main activity — sports after mental study is optimal. Hobbies foster self-efficacy, flow experiences, and intrinsic motivation — but only when time-limited and consciously planned, not serving as procrastination substitutes.',

  'psy.prokr.gaming.label': 'Gaming',
  'psy.prokr.gaming.q': 'Is gaming really harmful, or just a pastime like any other?',
  'psy.prokr.gaming.a': 'Gaming activates the dopaminergic reward system with variable-ratio reinforcement schedules — the most addictive reinforcement plan (Skinner). It becomes problematic through two mechanisms: First, hedonic adaptation — the natural dopamine baseline is downregulated, making studying feel less rewarding by comparison (Volkow et al., 2011). Second, opportunity costs: 3 hours of gaming daily = 1,095 hours/year — equivalent to 137 full workdays. Controlled gaming (max 5h/week) as a planned reward after fulfilled study goals therapeutically utilizes the Premack principle.',

  'psy.prokr.passiver_konsum.label': 'Passive Consumption',
  'psy.prokr.passiver_konsum.q': 'Why does streaming feel so satisfying even though you know it\'s unproductive?',
  'psy.prokr.passiver_konsum.a': 'Passive media consumption delivers low-threshold reward without effort — which appears ideal to the procrastinating brain (Tice et al., 2001: mood repair as motive). Narrative transportation (Green & Brock, 2000) creates immersion in fictional worlds that reduces stress short-term but exacerbates the problem long-term, as real stressors remain unresolved. Controlled use as reward (max 3h/week) with a predetermined endpoint and timer is the evidence-based recommendation.',

  'psy.prokr.ernaehrung_zucker.label': 'Sugar & Energy',
  'psy.prokr.ernaehrung_zucker.q': 'Can sugar really impair cognitive performance?',
  'psy.prokr.ernaehrung_zucker.a': 'Yes, through the glycemic cycle: high-glycemic food causes rapid blood sugar spike → insulin release → reactive hypoglycemia → energy crash, concentration loss, and cravings (Ludwig, 2002). Long-term, chronically high sugar consumption elevates inflammatory markers (CRP, IL-6) that promote neuroinflammation and cognitive impairment (Beilharz et al., 2015). Low-glycemic nutrition (oats, nuts, legumes) stabilizes blood sugar and cognitive performance throughout the day.',

  'psy.prokr.koerperpflege.label': 'Personal Care',
  'psy.prokr.koerperpflege.q': 'Does personal care actually affect psychological performance capacity?',
  'psy.prokr.koerperpflege.a': 'Yes — through the mechanism of enclothed cognition (Adam & Galinsky, 2012): clothing and appearance influence not only external perception but one\'s own cognitive performance. Participants wearing a doctor\'s coat showed significantly better attention performance. Personal care functions as a self-efficacy signal: the routine mastery of daily self-care strengthens sense of control and reduces helplessness — a central factor in depressive procrastination.',

  'psy.prokr.koerperhaltung.label': 'Posture',
  'psy.prokr.koerperhaltung.q': 'Can the way you sit really influence thinking and mood?',
  'psy.prokr.koerperhaltung.a': 'Embodied cognition confirms: posture influences emotion and cognition bidirectionally. While Carney et al.\'s (2010) "power poses" findings are debated regarding replication, Nair et al. (2015) confirmed: upright sitting significantly improves mood, self-esteem, and stress resilience compared to a slumped posture. Workplace ergonomics reduces musculoskeletal complaints that chronically impair concentration and endurance.',

  'psy.prokr.rhetorik.label': 'Communication',
  'psy.prokr.rhetorik.q': 'Why is communication ability often valued more highly than expertise?',
  'psy.prokr.rhetorik.a': 'Ambady and Rosenthal\'s thin-slicing research (1993) showed: people form judgments about competence, likability, and trustworthiness in fractions of a second — based on nonverbal behavior, not content. In professional contexts, communication competence correlates more strongly with career success than expertise (Harvard Business Review, 2012). Deliberate practice (Ericsson, 1993) — targeted, feedback-based practice — is the only empirically proven path to excellent rhetoric.',

  'psy.prokr.raumordnung.label': 'Order & Environment',
  'psy.prokr.raumordnung.q': 'Is tidying up actually productivity-relevant, or just aesthetic well-being?',
  'psy.prokr.raumordnung.a': 'More than aesthetics: visual clutter competes for attentional resources (McMains & Kastner, 2011, Princeton Neuroscience Institute). The brain processes irrelevant visual stimuli unconsciously — binding cognitive capacity and increasing error rates. Saxbe and Repetti (2010) found: individuals who described their home as "cluttered" showed flatter cortisol daily curves — a biomarker for chronic stress. Daily 5-minute tidying routines utilize habit stacking (Clear, 2018) and cumulatively reduce cognitive load.',

  'psy.prokr.gewohnheiten.label': 'Habits',
  'psy.prokr.gewohnheiten.q': 'Why is it so hard to break bad habits even when you really want to?',
  'psy.prokr.gewohnheiten.a': 'Habits are controlled by the basal ganglia — a phylogenetically ancient brain region storing automated action sequences (Graybiel, 2008). The habit loop (Duhigg, 2012) consists of cue → routine → reward. Willpower alone fails because it taxes prefrontal resources that are limited (ego depletion, Baumeister et al., 1998). Effective strategies: eliminate cues (stimulus control), replace the routine with a compatible alternative (substitution), change environmental design (choice architecture), and identity work: "I am someone who..." instead of "I\'m trying to..." (Clear, 2018: identity-based habits).',

  'psy.prokr.ernaehrung.label': 'Nutrition',
  'psy.prokr.ernaehrung.q': 'How strongly does nutrition actually influence cognitive performance?',
  'psy.prokr.ernaehrung.a': 'The brain consumes ~20% of basal metabolic rate at only 2% of body weight (Raichle & Gusnard, 2002). The PREDIMED study (2013, n=7,447) showed: Mediterranean diet significantly reduces cognitive decline, cardiovascular risk, and depression. Omega-3 fatty acids (DHA) are structural components of neuronal cell membranes. Low-glycemic-index breakfast improves working memory and attention (Ingwersen et al., 2007). Dehydration of just 2% body weight impairs attention and short-term memory (Ganio et al., 2011).',

  'psy.prokr.schlaf.label': 'Sleep',
  'psy.prokr.schlaf.q': 'Can\'t you really get by with less sleep if you use the time for studying instead?',
  'psy.prokr.schlaf.a': 'No — that is one of the best-documented illusions of self-assessment. Van Dongen et al. (2003) showed: individuals who chronically sleep 6 hours dramatically underestimate their cognitive impairment — after 14 days, their performance equals that of someone after 48h total sleep deprivation, while they feel "normal." Sleep is not lost time but active consolidation: the hippocampus replays learning content during deep sleep 20 times faster than during waking (Euston et al., 2007). 6h study + 8h sleep > 8h study + 6h sleep — consolidation makes the difference.',

  'psy.prokr.smartphone.label': 'Smartphone',
  'psy.prokr.smartphone.q': 'Is smartphone use really that problematic, or is that exaggerated?',
  'psy.prokr.smartphone.a': 'The evidence is clear: Ward et al. (2017, "Brain Drain") showed that the mere presence of a smartphone — even turned off — reduces working memory capacity and fluid intelligence. The mechanism: suppressing the impulse to reach for the phone consumes cognitive resources (ironic process theory, Wegner, 1994). Each notification creates an attention switch; Mark et al. (2008) showed: after an interruption, an average of 23 minutes and 15 seconds is needed to return to the original depth of concentration.',

  'psy.prokr.finanzen.label': 'Finances',
  'psy.prokr.finanzen.q': 'Why does financial stress cause disproportionate cognitive impairment?',
  'psy.prokr.finanzen.a': 'Mani et al. (2013, Science) showed: financial worries consume cognitive bandwidth needed for other tasks — the IQ effect equals that of a sleepless night or chronic alcoholism. Mullainathan and Shafir (2013) coined the term "scarcity mindset": scarcity tunnels attention to the immediate problem and reduces capacity for long-term planning. Automated saving, clear budget structures, and the 48-hour rule for impulse purchases reduce cognitive load and improve decision quality across all life domains.',

  'psy.prokr.summary.title': 'The Evidence-Based Core Message',
  'psy.prokr.summary.text':  'Procrastination is not a character flaw but an emotion regulation deficit. Research consistently shows: not willpower, but environmental design, implementation planning, and identity work are the most effective countermeasures. Every decision that prioritizes short-term relief over long-term well-being compounds — like compound interest, only against your own goals. The good news: neuroplasticity means new patterns can be established at any age. The best time to start was yesterday. The second-best is now.',
};

export default en;