// pages/projekte/lernzettel/eigenes/psychologie/js/translation/languages/es.js

const es = {
  /* ══════════════════════════════════════════════════════════
     HERO
     ══════════════════════════════════════════════════════════ */
  'psy.eyebrow':     'Compendio · Psicología',
  'psy.headline.1':  'Entender la psicología',
  'psy.headline.2':  'De la teoría al arte de vivir.',
  'psy.hero.desc':   'De la psicología profunda a la neurociencia — las perspectivas clave de la psicología, cómo se conectan y qué significan para la vida cotidiana y el desarrollo personal.',

  'psy.tab.tiefenpsychologie': 'Psicología profunda',
  'psy.tab.behaviorismus':     'Conductismo',
  'psy.tab.kognitive':         'Psicol. cognitiva',
  'psy.tab.humanistische':     'Psicol. humanista',
  'psy.tab.neurowissenschaft': 'Neurociencia',
  'psy.tab.sozialpsychologie': 'Psicología social',
  'psy.tab.prokrastination':   'Matriz de decisiones',

  'psy.footer.extra.title':     'Psicología y lecturas complementarias',
  'psy.footer.extra.back':      'Volver al resumen',
  'psy.footer.extra.portfolio': 'Portafolio',

  /* ══════════════════════════════════════════════════════════
     1 · PSICOLOGÍA PROFUNDA
     ══════════════════════════════════════════════════════════ */

  'psy.tiefenpsychologie.quote':        'Lo inconsciente es la verdadera realidad psíquica, tan desconocida para nosotros en su naturaleza interna como la realidad del mundo exterior.',
  'psy.tiefenpsychologie.quote.author': 'Sigmund Freud — La interpretación de los sueños, 1900',
  'psy.tiefenpsychologie.title':        'Psicología profunda',
  'psy.tiefenpsychologie.intro':        'La psicología profunda explora los procesos psíquicos inconscientes y sus efectos sobre la experiencia, el comportamiento y la salud mental. Fundada por Sigmund Freud y desarrollada por C.G. Jung, Alfred Adler y la teoría de las relaciones objetales, sigue siendo una de las corrientes más influyentes de la psicología clínica y los estudios culturales.',

  'psy.tiefenpsychologie.sec0.title': 'El modelo estructural de la psique: Ello, Yo y Superyó',
  'psy.tiefenpsychologie.sec0.text':  'En su segunda tópica (1923), Freud dividió la psique en tres instancias que interactúan dinámicamente.\n\nEl Ello (Id) representa el reservorio de energía pulsional — libido y destrudo — y opera según el principio del placer: satisfacción inmediata de las necesidades sin consideración de la realidad o la moral. Es completamente inconsciente y constituye la capa filogenéticamente más antigua de la personalidad.\n\nEl Yo (Ego) se desarrolla a partir del Ello mediante el contacto con el mundo exterior y opera según el principio de realidad. Media entre las exigencias pulsionales del Ello, los imperativos morales del Superyó y las demandas de la realidad. Freud comparó el Yo con un jinete que debe dirigir la fuerza superior del caballo (Ello).\n\nEl Superyó (Superego) surge mediante la interiorización de normas parentales y sociales, especialmente durante la resolución del complejo de Edipo. Abarca la conciencia moral (prohibiciones, culpa) y el ideal del yo (modelos, estándares de valor). Un Superyó excesivamente estricto produce culpa neurótica; uno demasiado débil conduce a conductas antisociales.\n\nLos conflictos psíquicos surgen inevitablemente, ya que las tres instancias plantean exigencias incompatibles. El Yo debe mediar permanentemente estos conflictos — Freud lo llamó por eso «servidor de tres amos».',

  'psy.tiefenpsychologie.sec1.title': 'Mecanismos de defensa: la autorregulación inconsciente',
  'psy.tiefenpsychologie.sec1.text':  'Anna Freud sistematizó en «El yo y los mecanismos de defensa» (1936) las estrategias con las que el Yo reduce la ansiedad intolerable. Operan de forma inconsciente y distorsionan la realidad en grados variables.\n\nLa represión constituye el mecanismo de defensa primario: impulsos amenazantes, recuerdos o afectos son activamente impedidos de acceder a la consciencia. El contenido reprimido no se borra — se manifiesta en actos fallidos, sueños y síntomas.\n\nLa proyección externaliza los propios impulsos inaceptables: la propia agresión se experimenta como hostilidad del entorno; los propios deseos sexuales se atribuyen a otros.\n\nLa formación reactiva transforma el impulso prohibido en su opuesto: el odio se convierte en amabilidad excesiva, los deseos sexuales en rigidez puritana.\n\nLa sublimación se considera la defensa «más madura»: la energía pulsional se redirige hacia canales socialmente aceptables — la agresión hacia la competición deportiva, la energía sexual hacia la creación artística.\n\nOtros mecanismos incluyen racionalización, regresión, desplazamiento e intelectualización.\n\nLa defensa es fundamentalmente adaptativa — se vuelve patológica solo cuando se emplea de forma rígida, excesiva y distorsionando la realidad.',

  'psy.tiefenpsychologie.sec2.title': 'C.G. Jung: psicología analítica, arquetipos e individuación',
  'psy.tiefenpsychologie.sec2.text':  'Carl Gustav Jung (1875–1961) amplió el modelo freudiano con una dimensión transpersonal. Su concepto central es el inconsciente colectivo — una capa psíquica profunda que contiene patrones experienciales de la historia de la humanidad, específicos de la especie.\n\nLos arquetipos son los elementos estructurales del inconsciente colectivo. Se manifiestan en mitos, sueños, símbolos religiosos y motivos transculturales. Los más importantes:\n\n— La Sombra: aspectos de la personalidad reprimidos y valorados negativamente. La integración de la Sombra es el primer paso hacia la individuación. «No se alcanza la iluminación imaginando figuras de luz, sino haciendo consciente la oscuridad» (Jung).\n\n— Ánima y Ánimus: el principio contrasexual inconsciente — el Ánima como elemento femenino en el hombre, el Ánimus como elemento masculino en la mujer. Su proyección moldea la elección de pareja y la calidad de las relaciones.\n\n— El Sí-mismo (Self): el arquetipo de la totalidad y meta del proceso de individuación. Unifica los aspectos conscientes e inconscientes de la personalidad.\n\nLa individuación describe el proceso de toda una vida de llegar a ser uno mismo: la integración gradual de Sombra, Ánima/Ánimus y otros arquetipos en una imagen de personalidad consciente y holística.',

  'psy.tiefenpsychologie.sec3.title': 'Adler: psicología individual, sentimiento de comunidad y estilo de vida',
  'psy.tiefenpsychologie.sec3.text':  'Alfred Adler (1870–1937) fundó la psicología individual como escuela independiente que contempla al ser humano como unidad indivisible (lat. individuum) en su contexto social.\n\nEl sentimiento de inferioridad y la compensación forman la teoría motivacional central de Adler. Todo niño experimenta inferioridad orgánica, intelectual o social. Este sentimiento básico genera un afán de superación — la compensación. La compensación saludable conduce a logros y creatividad; la sobrecompensación patológica se manifiesta como afán de poder, narcisismo o repliegue.\n\nEl sentimiento de comunidad (social interest) es el concepto ético y terapéutico nuclear de Adler. Definió la salud mental como la capacidad de abordar cooperativamente las tres tareas vitales — trabajo, amor y comunidad. La neurosis la interpretó como «fracaso ante las tareas vitales» por falta de sentimiento de comunidad.\n\nEl estilo de vida se forma en los primeros seis años y abarca las creencias, metas y estrategias individuales con las que una persona busca superar su inferioridad subjetivamente experimentada. Aaron T. Beck llamó a Adler «el bisabuelo de la terapia cognitiva».',

  /* ══════════════════════════════════════════════════════════
     2 · CONDUCTISMO
     ══════════════════════════════════════════════════════════ */

  'psy.behaviorismus.quote':        'Dadme una docena de niños sanos, bien formados, y mi propio mundo para criarlos, y garantizo que tomaré uno al azar y lo entrenaré para convertirse en cualquier tipo de especialista — médico, abogado, artista, comerciante, e incluso mendigo y ladrón.',
  'psy.behaviorismus.quote.author': 'John B. Watson — Behaviorism, 1924',
  'psy.behaviorismus.title':        'Conductismo',
  'psy.behaviorismus.intro':        'El conductismo estableció la psicología como ciencia natural objetiva al limitarse al comportamiento observable y medible. Los estados internos como la conciencia, los sentimientos o los motivos se consideraban científicamente inaccesibles — solo era relevante la relación funcional entre estímulos ambientales (S) y respuestas conductuales (R).',

  'psy.behaviorismus.sec0.title': 'Condicionamiento clásico: Pávlov, Watson y las leyes de la asociación',
  'psy.behaviorismus.sec0.text':  'Iván Petróvich Pávlov (1849–1936) descubrió un principio fundamental de aprendizaje durante sus experimentos digestivos con perros: cuando un estímulo originalmente neutro (EN) se presenta repetidamente junto con un estímulo incondicionado (EI), adquiere la capacidad de provocar una respuesta condicionada (RC) — convirtiéndose en estímulo condicionado (EC).\n\nLa adquisición sigue una curva de aprendizaje negativamente acelerada. Rescorla y Wagner (1972) demostraron que no la mera contigüidad (coincidencia temporal) es decisiva, sino la contingencia — el valor informativo del EC respecto a la aparición del EI.\n\nLa extinción ocurre cuando el EC se presenta repetidamente sin el EI. La respuesta condicionada desaparece pero no se borra: la recuperación espontánea demuestra que la asociación original se mantiene latente.\n\nJohn B. Watson demostró en el éticamente controvertido experimento del «Pequeño Albert» (1920) que las respuestas de miedo pueden condicionarse clásicamente en humanos — una base para comprender fobias y trastornos de ansiedad.',

  'psy.behaviorismus.sec1.title': 'Condicionamiento operante: Thorndike, Skinner y el control por consecuencias',
  'psy.behaviorismus.sec1.text':  'Edward Lee Thorndike (1874–1949) formuló la «Ley del Efecto»: las conductas que producen un estado satisfactorio se fortalecen; las que producen uno desagradable se debilitan.\n\nB.F. Skinner (1904–1990) sistematizó este principio como condicionamiento operante. La conducta se controla por sus consecuencias:\n\n— Refuerzo positivo: un estímulo agradable sigue a la conducta → la frecuencia aumenta.\n— Refuerzo negativo: un estímulo aversivo es eliminado por la conducta → la frecuencia aumenta.\n— Castigo positivo (tipo I): un estímulo aversivo sigue a la conducta → la frecuencia disminuye.\n— Castigo negativo (tipo II): un estímulo agradable se retira → la frecuencia disminuye.\n\nLos programas de refuerzo determinan la resistencia a la extinción: el refuerzo continuo produce aprendizaje rápido pero baja resistencia. El refuerzo intermitente (programas de razón o intervalo variable) produce altas tasas de respuesta y extrema resistencia a la extinción — el principio detrás de la adicción al juego y los algoritmos de redes sociales.',

  'psy.behaviorismus.sec2.title': 'Teoría del aprendizaje social-cognitivo: Bandura y la superación del paradigma E-R',
  'psy.behaviorismus.sec2.text':  'Albert Bandura (1925–2021) trascendió los límites del conductismo clásico con su teoría del aprendizaje social-cognitivo al introducir variables cognitivas como mediadoras entre estímulo y respuesta.\n\nEl experimento del muñeco Bobo (1961) demostró el aprendizaje por observación: niños que observaron un modelo agresivo mostraron significativamente más conductas agresivas que los grupos de control — sin refuerzo directo. Bandura identificó cuatro subprocesos: atención, retención, reproducción motora y motivación.\n\nEl determinismo recíproco postula que conducta, persona (esquemas cognitivos, creencias) y ambiente se influyen mutuamente.\n\nLa autoeficacia es el concepto más influyente de Bandura: la creencia subjetiva en la propia capacidad para ejecutar exitosamente una acción específica. Cuatro fuentes la alimentan: experiencias de dominio (fuente más poderosa), experiencia vicaria, persuasión verbal y estados fisiológicos/afectivos. Los meta-análisis confirman que la autoeficacia es uno de los predictores más fuertes de rendimiento, conducta de salud y manejo del estrés.',

  'psy.behaviorismus.sec3.title': 'Aplicación clínica: terapia conductual basada en evidencia',
  'psy.behaviorismus.sec3.text':  'La terapia conductual traduce principios de la teoría del aprendizaje en intervenciones clínicas y es una de las formas de terapia con mayor validación empírica.\n\nDesensibilización sistemática (Wolpe, 1958): tratamiento de trastornos de ansiedad mediante exposición gradual a estímulos ansiógenos con relajación muscular simultánea.\n\nExposición con prevención de respuesta (EPR): estándar de oro para TOC y fobias específicas.\n\nActivación conductual: para la depresión, se incrementan sistemáticamente las actividades placenteras y de dominio — los meta-análisis muestran tamaños de efecto comparables a los antidepresivos.',

  /* ══════════════════════════════════════════════════════════
     3 · PSICOLOGÍA COGNITIVA
     ══════════════════════════════════════════════════════════ */

  'psy.kognitive.quote':        'No nos perturban las cosas mismas, sino los juicios y opiniones que tenemos sobre ellas.',
  'psy.kognitive.quote.author': 'Epicteto — Enquiridión, ca. 125 d.C. (idea fundacional de la terapia cognitiva)',
  'psy.kognitive.title':        'Psicología cognitiva',
  'psy.kognitive.intro':        'La psicología cognitiva examina los procesos mentales que median entre la entrada de estímulos y la respuesta conductual: percepción, atención, memoria, lenguaje, resolución de problemas y formación de juicios. Modela al ser humano como un sistema de procesamiento de información y constituye el fundamento teórico de la terapia cognitivo-conductual.',

  'psy.kognitive.sec0.title': 'Sesgos cognitivos y heurísticas: la arquitectura del pensamiento erróneo',
  'psy.kognitive.sec0.text':  'El programa de investigación de Amos Tversky y Daniel Kahneman (desde 1971) revolucionó la comprensión del juicio humano. Identificaron desviaciones sistemáticas de las normas racionales — sesgos cognitivos resultantes del uso de heurísticas rápidas pero propensas a error.\n\nHeurística de disponibilidad: la probabilidad de un evento se juzga según la facilidad con que se pueden recuperar ejemplos de la memoria. Eventos sobrerepresentados mediáticamente (accidentes aéreos) se sobreestiman; estadísticamente más frecuentes (accidentes automovilísticos) se subestiman.\n\nEfecto de anclaje: un valor de referencia inicial (ancla) influye en todos los juicios posteriores, incluso cuando el ancla es obviamente irrelevante.\n\nSesgo de confirmación: la tendencia a buscar, interpretar y recordar información que confirma creencias preexistentes.\n\nEfecto Dunning-Kruger: personas con baja competencia sobreestiman sistemáticamente sus capacidades, mientras que las altamente competentes subestiman su rendimiento.\n\nEstos sesgos no son defectos sino atajos evolutivamente adaptativos que generalmente funcionan bajo presión temporal e incertidumbre — pero producen errores sistemáticos en entornos de decisión complejos y modernos.',

  'psy.kognitive.sec1.title': 'Sistemas de memoria: del registro sensorial al almacén a largo plazo',
  'psy.kognitive.sec1.text':  'El modelo multialmacén de Atkinson y Shiffrin (1968) distingue tres etapas secuenciales del procesamiento de información.\n\nEl registro sensorial (icónico/ecoico) almacena impresiones sensoriales no procesadas durante fracciones de segundo. El procedimiento de informe parcial de Sperling (1960) demostró que la capacidad es mucho mayor que lo que puede reportarse conscientemente.\n\nLa memoria a corto plazo / memoria de trabajo mantiene información en procesamiento activo. El «número mágico siete» de Miller (1956) describió la limitación de capacidad a 7±2 unidades. Baddeley y Hitch (1974) expandieron el concepto al modelo de memoria de trabajo con bucle fonológico, agenda visuoespacial y ejecutivo central.\n\nLa memoria a largo plazo tiene capacidad prácticamente ilimitada. Tulving (1972) distinguió memoria episódica, semántica y procedimental. La consolidación es controlada por el hipocampo y potenciada por el sueño, la elaboración y la significación emocional.\n\nEl efecto de evaluación (Roediger & Karpicke, 2006) muestra: la recuperación activa es más efectiva que la relectura. El efecto de espaciado y la intercalación optimizan la retención a largo plazo — estrategias basadas en evidencia que superan significativamente los métodos de estudio tradicionales.',

  'psy.kognitive.sec2.title': 'Terapia cognitiva: Beck, Ellis y la reestructuración terapéutica',
  'psy.kognitive.sec2.text':  'Aaron T. Beck (1921–2021) desarrolló la terapia cognitiva (TC) a partir de la observación clínica de que los pacientes depresivos muestran errores de pensamiento característicos.\n\nEl modelo cognitivo postula tres niveles de cognición disfuncional:\n\n1. Pensamientos automáticos: evaluaciones espontáneas y fugaces que a menudo pasan desapercibidas pero controlan directamente emociones y conducta.\n\n2. Distorsiones cognitivas: sobregeneralización, pensamiento dicotómico, catastrofización y personalización.\n\n3. Creencias nucleares y esquemas: convicciones profundamente arraigadas sobre uno mismo, los demás y el mundo, formadas en la infancia.\n\nLa tríada cognitiva de la depresión de Beck: esquemas negativos sobre el yo («Soy un inútil»), el mundo («El mundo es hostil») y el futuro («Nunca mejorará»).\n\nAlbert Ellis desarrolló paralelamente la Terapia Racional Emotiva Conductual (TREC) con el modelo ABC: no es el evento activador (A) el que causa la consecuencia emocional (C), sino la creencia irracional (B).\n\nLa terapia cognitivo-conductual (TCC) es la forma de psicoterapia con mayor respaldo empírico, con eficacia demostrada en depresión, trastornos de ansiedad, TEPT, trastornos alimentarios y dolor crónico.',

  'psy.kognitive.sec3.title': 'Teoría del proceso dual: dos sistemas de pensamiento',
  'psy.kognitive.sec3.text':  'La teoría del proceso dual de Daniel Kahneman (resumida en «Pensar rápido, pensar despacio», 2011) distingue dos modos fundamentales de procesamiento.\n\nEl Sistema 1 opera rápida, automática, sin esfuerzo e inconscientemente. Procesa rostros, reconoce emociones, completa frases y controla acciones cotidianas. Utiliza heurísticas y es susceptible a sesgos sistemáticos.\n\nEl Sistema 2 es lento, controlado, esforzado y consciente. Se activa para cálculos complejos, razonamiento lógico, autocontrol y verificación de juicios del Sistema 1. Tiene capacidad limitada — se fatiga fácilmente.\n\nInsight central de Kahneman: la mayoría de los sesgos cognitivos surgen porque el Sistema 1 asume problemas que realmente requieren el Sistema 2 — y el Sistema 2 es demasiado «perezoso» o está demasiado agotado para intervenir.\n\nLa teoría tiene implicaciones de gran alcance para el nudging (Thaler & Sunstein), la economía conductual, el diagnóstico médico y la comunicación de riesgos.',

  /* ══════════════════════════════════════════════════════════
     4 · PSICOLOGÍA HUMANISTA
     ══════════════════════════════════════════════════════════ */

  'psy.humanistische.quote':        'Lo que un hombre puede ser, debe serlo. Debe permanecer fiel a su propia naturaleza.',
  'psy.humanistische.quote.author': 'Abraham Maslow — Motivación y personalidad, 1954',
  'psy.humanistische.title':        'Psicología humanista',
  'psy.humanistische.intro':        'La psicología humanista surgió en los años 60 como la «tercera fuerza» junto al psicoanálisis y el conductismo. Enfatiza las capacidades humanas únicas para la autorreflexión, la libre elección y la búsqueda de sentido, situando el potencial positivo de crecimiento en el centro — en lugar de la patología y los déficits.',

  'psy.humanistische.sec0.title': 'La jerarquía de necesidades de Maslow y el concepto de autorrealización',
  'psy.humanistische.sec0.text':  'Abraham Maslow (1908–1970) organizó las necesidades humanas en una estructura jerárquica comúnmente visualizada como una pirámide:\n\n1. Necesidades fisiológicas: alimentación, agua, sueño, homeostasis.\n2. Necesidades de seguridad: seguridad física, estabilidad financiera, salud, orden.\n3. Necesidades sociales (pertenencia y amor): amistad, intimidad, vínculos familiares.\n4. Necesidades de estima: reconocimiento, experiencia de competencia, autorrespeto.\n5. Autorrealización: la actualización del propio potencial.\n\nMaslow estudió personalidades ejemplares (Lincoln, Einstein, Eleanor Roosevelt) e identificó rasgos de personas autorrealizadas: orientación a problemas, autonomía, experiencias cumbre (peak experiences) y orientación democrática de valores.\n\nCríticas: la jerarquía estricta no se confirma empíricamente de manera consistente; el orden de necesidades está culturalmente condicionado. No obstante, el modelo sigue siendo uno de los conceptos más influyentes en psicología, educación y gestión.',

  'psy.humanistische.sec1.title': 'Rogers: terapia centrada en la persona y el concepto de congruencia',
  'psy.humanistische.sec1.text':  'Carl R. Rogers (1902–1987) desarrolló la terapia centrada en la persona, basada en tres condiciones necesarias y suficientes para el cambio terapéutico:\n\n1. Empatía (comprensión empática): el terapeuta se introduce en el mundo experiencial interno del cliente y comunica esa comprensión.\n\n2. Congruencia (autenticidad): el terapeuta es auténtico en la relación — su experiencia, conciencia y comunicación están alineadas.\n\n3. Aceptación positiva incondicional: el terapeuta acepta al cliente como persona sin condiciones.\n\nRogers postuló la tendencia actualizante como único principio motivacional básico: todo organismo tiende naturalmente hacia el crecimiento y la autonomía. Los trastornos psicológicos surgen por la incongruencia — la discrepancia entre el autoconcepto y la experiencia organísmica real.\n\nLas condiciones de valor, internalizadas en la infancia, llevan a las personas a negar o distorsionar partes de su experiencia. La terapia crea, mediante las tres condiciones nucleares, un espacio donde el cliente puede percibirse y aceptarse sin distorsión.',

  'psy.humanistische.sec2.title': 'Psicología positiva: Seligman, PERMA y la ciencia del florecimiento',
  'psy.humanistische.sec2.text':  'Martin Seligman (*1942) fundó en 1998 la psicología positiva como programa de investigación científica de lo que hace florecer a las personas — bienestar en lugar de patología.\n\nEl modelo PERMA identifica cinco pilares empíricamente medibles del bienestar:\n\n— Positive Emotions: alegría, gratitud, interés, esperanza — la teoría broaden-and-build de Barbara Fredrickson muestra que las emociones positivas amplían el repertorio de acción y construyen recursos psicológicos.\n— Engagement: absorción profunda en actividades (flujo).\n— Relationships: vínculos sociales cualitativos como el predictor más fuerte de satisfacción vital — el Estudio Harvard de Desarrollo Adulto (desde 1938) lo confirma durante 85 años.\n— Meaning: el sentimiento de ser parte de algo mayor — conectado con la logoterapia de Viktor Frankl.\n— Achievement: rendimiento y experiencia de competencia por sí mismos — investigación de Angela Duckworth sobre «grit» (perseverancia).\n\nInvestigación de fortalezas de carácter (Peterson & Seligman, 2004): la clasificación VIA identifica 24 fortalezas universales. Los estudios de intervención muestran que el uso consciente de las fortalezas de firma aumenta el bienestar y reduce los síntomas depresivos.',

  'psy.humanistische.sec3.title': 'Teoría del flujo: Csikszentmihalyi y la psicología de la experiencia óptima',
  'psy.humanistische.sec3.text':  'Mihaly Csikszentmihalyi (1934–2021) investigó desde los 70 el estado de flujo — la experiencia de absorción total en una actividad donde desaparece el sentido del tiempo, la autoconciencia retrocede y la motivación intrínseca alcanza su pico.\n\nOcho componentes del flujo según Csikszentmihalyi:\n1. Equilibrio entre desafío y habilidad\n2. Fusión de acción y conciencia\n3. Metas claras\n4. Retroalimentación inmediata\n5. Concentración en la tarea\n6. Sensación de control\n7. Pérdida de la consciencia autorreflexiva\n8. Alteración del sentido del tiempo\n\nEl canal de flujo: cuando las demandas exceden las habilidades → ansiedad; cuando las habilidades exceden las demandas → aburrimiento. El flujo surge en el equilibrio dinámico.\n\nCorrelatos neurocientíficos: en el flujo se observa hipofrontalidad transitoria — una regulación a la baja del córtex prefrontal que reduce la autocrítica y permite la acción fluida y sin esfuerzo (Dietrich, 2004).\n\nImplicación práctica: el flujo es entrenable. El ajuste sistemático de los desafíos al nivel de habilidad propio crea estados óptimos de aprendizaje y rendimiento.',

  /* ══════════════════════════════════════════════════════════
     5 · NEUROCIENCIA
     ══════════════════════════════════════════════════════════ */

  'psy.neurowissenschaft.quote':        'Somos nuestro cerebro — pero nuestro cerebro es más de lo que creemos ser.',
  'psy.neurowissenschaft.quote.author': 'Dick Swaab — Somos nuestro cerebro, 2010',
  'psy.neurowissenschaft.title':        'Neurociencia',
  'psy.neurowissenschaft.intro':        'La neurociencia investiga cómo el sistema nervioso produce comportamiento, cognición y emoción. Integra hallazgos de neuroanatomía, neurofisiología, neuroquímica, neuroimagen y neurociencia computacional en una comprensión biológica de los procesos psíquicos.',

  'psy.neurowissenschaft.sec0.title': 'Transmisión de señales neuronales: potenciales de acción, sinapsis y neurotransmisores',
  'psy.neurowissenschaft.sec0.text':  'El cerebro humano contiene aproximadamente 86 mil millones de neuronas (Azevedo et al., 2009) que se comunican a través de entre 100 y 500 billones de sinapsis — el sistema más complejo conocido en el universo.\n\nTransmisión eléctrica: el potencial de acción es una señal de todo o nada que se propaga a lo largo del axón mediante el ingreso secuencial de iones Na⁺ (despolarización) y la salida de K⁺ (repolarización). La mielinización acelera la conducción hasta 120 m/s mediante conducción saltatoria.\n\nTransmisión química: en la sinapsis, la señal eléctrica se convierte en química. Los neurotransmisores se liberan desde vesículas presinápticas y se unen a receptores postsinápticos.\n\nNeurotransmisores clave:\n— Dopamina: expectativa de recompensa, motivación, control motor. La señal de error de predicción de recompensa (Schultz, 1997): la dopamina codifica no la recompensa en sí, sino la desviación de la recompensa respecto a la expectativa.\n— Serotonina (5-HT): regulación del ánimo, control de impulsos. Los ISRS son el tratamiento de primera línea para la depresión.\n— GABA: principal neurotransmisor inhibidor. Las benzodiacepinas actúan ansiolíticamente a través de receptores GABA-A.\n— Glutamato: principal neurotransmisor excitador. Los receptores NMDA son esenciales para la potenciación a largo plazo (PLP) — el mecanismo sináptico del aprendizaje y la memoria.',

  'psy.neurowissenschaft.sec1.title': 'Neuroplasticidad: el cerebro como órgano autorreconstructivo',
  'psy.neurowissenschaft.sec1.text':  'La neuroplasticidad — la modificación dependiente de la experiencia de estructuras y funciones neuronales — ha revolucionado la imagen estática del cerebro adulto.\n\nPlasticidad sináptica: el postulado de Hebb (1949) — «las neuronas que se activan juntas se conectan juntas» — describe el fortalecimiento dependiente de la actividad de las conexiones sinápticas (PLP). Las conexiones no utilizadas se debilitan (poda sináptica, DLP).\n\nPlasticidad estructural: Maguire et al. (2000) mostraron un hipocampo posterior agrandado en taxistas londinenses — proporcional a los años de experiencia. Los músicos muestran córtex auditivos agrandados.\n\nNeurogénesis adulta: contrariamente al viejo dogma, se generan nuevas neuronas a lo largo de toda la vida en el hipocampo. La actividad física, la estimulación cognitiva y los entornos enriquecidos promueven la neurogénesis; el estrés crónico y la falta de sueño la inhiben.\n\nRelevancia clínica: la neuroplasticidad es la base biológica de toda psicoterapia. La TCC modifica demostrablemente la actividad del córtex prefrontal y la amígdala (Goldapple et al., 2004). La meditación mindfulness engrosa el córtex prefrontal (Hölzel et al., 2011).',

  'psy.neurowissenschaft.sec2.title': 'El cerebro emocional: sistema límbico, eje del estrés y regulación afectiva',
  'psy.neurowissenschaft.sec2.text':  'La amígdala es la estructura central para el procesamiento de la significación emocional, particularmente de la amenaza y el miedo. LeDoux (1996) identificó dos vías:\n\n— La «vía baja» (ruta tálamo-amigdalar): detección rápida y grosera de amenazas.\n— La «vía alta» (ruta tálamo-cortical-amigdalar): análisis lento y diferenciado con posibilidad de reevaluación contextual.\n\nEl córtex prefrontal (CPF) regula las reacciones emocionales de arriba abajo — permite la reevaluación cognitiva, el control de impulsos y la supresión de reacciones inapropiadas.\n\nEl eje HHA (hipotalámico-hipofisario-adrenal): ante el estrés, el hipotálamo activa la liberación de CRH → la hipófisis libera ACTH → la corteza adrenal produce cortisol. El estrés agudo moviliza energía. El estrés crónico:\n— Daña neuronas hipocampales (Sapolsky, 2004)\n— Potencia la reactividad de la amígdala\n— Debilita el CPF → autorregulación reducida\n— Suprime el sistema inmunológico\n\nLa teoría polivagal (Porges, 2011) describe tres patrones jerárquicos de respuesta ante amenazas: implicación social (vago ventral), lucha/huida (simpático) y congelación (vago dorsal).',

  'psy.neurowissenschaft.sec3.title': 'Sueño y rendimiento cognitivo: consolidación, homeostasis y ritmos circadianos',
  'psy.neurowissenschaft.sec3.text':  'El sueño es un proceso neurobiológico activo y altamente estructurado, esencial para la función cognitiva, la regulación emocional y la salud física.\n\nArquitectura del sueño: un ciclo (~90 min) atraviesa las fases N1 (adormecimiento), N2 (sueño ligero con husos del sueño), N3 (sueño profundo/ondas lentas) y sueño REM. Se completan 4–6 ciclos por noche.\n\nConsolidación de la memoria: Walker y Stickgold (2004) mostraron que diferentes fases del sueño fortalecen diferentes sistemas de memoria:\n— Sueño profundo (N3): consolidación de memorias declarativas — el hipocampo «reproduce» las experiencias diurnas y las transfiere al neocórtex.\n— Sueño REM: consolidación de memorias procedimentales y emocionales, resolución creativa de problemas.\n\nSistema glinfático (Nedergaard, 2012): durante el sueño, los espacios entre las células cerebrales se expanden un 60%, permitiendo la eliminación de productos metabólicos neurotóxicos (incluyendo beta-amiloide).\n\nPrivación de sueño: una noche con 6h de sueño reduce el rendimiento cognitivo en ~30%. La reactividad de la amígdala aumenta un 60% tras la privación de sueño (Yoo et al., 2007). 4–5h de sueño reducen la actividad de las células NK en un 70%.',

  /* ══════════════════════════════════════════════════════════
     6 · PSICOLOGÍA SOCIAL
     ══════════════════════════════════════════════════════════ */

  'psy.sozialpsychologie.quote':        'No vemos las cosas como son — las vemos como somos nosotros.',
  'psy.sozialpsychologie.quote.author': 'Anaïs Nin — Seducción del Minotauro, 1961',
  'psy.sozialpsychologie.title':        'Psicología social',
  'psy.sozialpsychologie.intro':        'La psicología social estudia cómo los pensamientos, sentimientos y comportamientos de las personas son influidos por la presencia real, imaginada o implícita de otros (Allport, 1954). Combina la metodología experimental con el análisis de fenómenos sociales.',

  'psy.sozialpsychologie.sec0.title': 'Conformidad y obediencia: Asch, Milgram y el poder de la situación',
  'psy.sozialpsychologie.sec0.text':  'Experimento de conformidad de Solomon Asch (1951): los participantes debían comparar longitudes de líneas — una tarea trivial. Sin embargo, cuando los cómplices daban respuestas deliberadamente erróneas, el 75% de los participantes se conformó al menos una vez.\n\nAsch distinguió la influencia social informativa (adoptar la opinión de otros porque se cree correcta) y la influencia social normativa (conformarse para asegurar pertenencia y evitar rechazo).\n\nExperimento de obediencia de Stanley Milgram (1963): el 65% de los participantes administró descargas eléctricas aparentemente letales de 450 voltios por instrucción de una figura de autoridad — a pesar de que el «aprendiz» (cómplice) expresaba dolor claramente.\n\nMilgram identificó factores situacionales que aumentaban la obediencia: proximidad a la autoridad, distancia de la víctima, legitimidad institucional y escalada gradual.\n\nExperimento de la prisión de Stanford de Zimbardo (1971): demostró cuán rápidamente las asignaciones de rol pueden determinar el comportamiento. Zimbardo formuló el «efecto Lucifer»: no las «personas malvadas» producen «actos malvados», sino los «sistemas malvados» corrompen a personas ordinarias.',

  'psy.sozialpsychologie.sec1.title': 'Pensamiento grupal, identidad social y conflicto intergrupal',
  'psy.sozialpsychologie.sec1.text':  'Irving Janis (1972) acuñó el término Groupthink: en grupos cohesivos con fuerte presión de consenso surgen patologías de decisión — ilusión de invulnerabilidad, racionalización colectiva, estereotipación del exogrupo, autocensura e ilusión de unanimidad.\n\nLa Teoría de la Identidad Social de Tajfel (1979) explica cómo la pertenencia grupal moldea el autoconcepto y el comportamiento:\n\n1. Categorización social: las personas se clasifican a sí mismas y a otros en grupos.\n2. Identificación social: la pertenencia al grupo se convierte en parte del autoconcepto.\n3. Comparación social: los grupos se comparan, con una mejora sistemática del propio.\n\nEl paradigma del grupo mínimo (Tajfel et al., 1971) mostró: incluso con asignación grupal arbitraria, surge el favoritismo endogrupal — la mera categorización es suficiente.\n\nHipótesis de contacto de Allport (1954): los prejuicios se reducen mediante contacto intergrupal bajo condiciones específicas: estatus igual, metas comunes, apoyo institucional y cooperación. El meta-análisis de Pettigrew y Tropp (2006, 515 estudios) confirmó robustamente el efecto de contacto.',

  'psy.sozialpsychologie.sec2.title': 'Disonancia cognitiva: la teoría de Festinger sobre las contradicciones internas',
  'psy.sozialpsychologie.sec2.text':  'La teoría de la disonancia cognitiva de Leon Festinger (1957): cuando dos cogniciones (creencias, actitudes, conocimiento sobre el propio comportamiento) son inconsistentes, surge un estado de tensión aversivo — disonancia cognitiva — que la persona está motivada a reducir.\n\nEstrategias de reducción: cambio de actitud, cambio de conducta, adición de cogniciones consonantes, trivialización.\n\nExperimento clásico de cumplimiento forzado (Festinger & Carlsmith, 1959): participantes que describieron una tarea aburrida como interesante por solo $1 (justificación externa insuficiente) cambiaron su actitud más que quienes recibieron $20.\n\nAplicaciones: disonancia posdecisional, justificación del esfuerzo, exposición selectiva (consumo preferente de medios consistentes con las actitudes — «cámaras de eco»).',

  'psy.sozialpsychologie.sec3.title': 'Conducta prosocial, efecto espectador y la psicología de la ayuda',
  'psy.sozialpsychologie.sec3.text':  'El efecto espectador fue investigado experimentalmente por Darley y Latané tras el asesinato de Kitty Genovese (1964). Hallazgo: cuantos más testigos hay en una emergencia, menor la probabilidad de que alguien ayude.\n\nTres mecanismos psicológicos:\n1. Difusión de responsabilidad: «Alguien más ayudará».\n2. Ignorancia pluralista: en situaciones ambiguas, la gente se guía por el comportamiento de otros.\n3. Aprensión evaluativa: el temor a avergonzarse con una acción inapropiada.\n\nModelo de 5 etapas de la ayuda de Latané y Darley: (1) notar la situación → (2) interpretarla como emergencia → (3) asumir responsabilidad personal → (4) percibir competencia para ayudar → (5) decidir actuar.\n\nFactores de conducta prosocial: empatía (Batson, 1991), normas personales, similitud percibida con el necesitado, buen humor (Isen & Levin, 1972), bajos costos de ayudar y opciones de acción claras.',

  /* ══════════════════════════════════════════════════════════
     7 · PROCRASTINACIÓN — Matriz de decisiones
     17 áreas universales como diálogos
     ══════════════════════════════════════════════════════════ */

  'psy.prokr.quote':        'La procrastinación no es un problema de gestión del tiempo — es un problema de regulación emocional.',
  'psy.prokr.quote.author': 'Timothy Pychyl — Solving the Procrastination Puzzle, 2013',
  'psy.prokr.title':        'Matriz de decisiones: superar la procrastinación',
  'psy.prokr.intro':        'La procrastinación es el aplazamiento irracional de acciones a pesar de conocer las consecuencias negativas. Las investigaciones de Pychyl, Steel y Sirois muestran: se trata de un trastorno de la regulación emocional — el afecto a corto plazo se prioriza a expensas de los objetivos a largo plazo. La siguiente matriz confronta 17 áreas vitales centrales con hallazgos científicos.',

  'psy.prokr.impact': 'Impacto',

  'psy.prokr.bildung.label': 'Educación',
  'psy.prokr.bildung.q': '¿Por qué cuesta tanto ponerse a estudiar, aun conociendo las consecuencias?',
  'psy.prokr.bildung.a': 'La Temporal Motivation Theory de Steel (2007) explica: la motivación disminuye exponencialmente con la distancia temporal de la recompensa (temporal discounting). Los exámenes en semanas motivan menos que YouTube ahora. La solución son los implementation plans (Gollwitzer, 1999): planes concretos si-entonces («Cuando sean las 15:00, abro el libro de química») aumentan la probabilidad de ejecución en un 40–60%, al eliminar la carga de decisión del momento.',

  'psy.prokr.morgenroutine.label': 'Rutina matutina',
  'psy.prokr.morgenroutine.q': '¿Levantarse más temprano realmente ayuda — o es solo un mito de la cultura de productividad?',
  'psy.prokr.morgenroutine.a': 'Cronobiológicamente, el pico de rendimiento cognitivo para la mayoría (cronotipo «alondra») se sitúa 2–4 horas después de despertar (Valdez et al., 2012). Dormir durante esta fase significa perder el segmento más productivo del día. La clave es la consistencia: horarios irregulares desincroniza el ritmo circadiano — un efecto descrito como «jet lag social» (Wittmann et al., 2006). Levantarse 90 minutos antes manteniendo la duración del sueño produce ~550 horas extra al año.',

  'psy.prokr.mentale_kompetenz.label': 'Fortaleza mental',
  'psy.prokr.mentale_kompetenz.q': '¿Cómo dejar de paralizarse por pensamientos negativos?',
  'psy.prokr.mentale_kompetenz.a': 'El modelo cognitivo de Beck muestra: no son los eventos los que causan emociones, sino su evaluación (modelo ABC). La terapia metacognitiva (Wells, 2009) va más allá: el problema no es el pensamiento negativo en sí, sino la reacción — rumiación y preocupación como estrategias de afrontamiento desadaptativas. El entrenamiento en defusión cognitiva (ACT) y la escritura expresiva (Pennebaker, 1997) — 15 minutos de diario sobre experiencias angustiantes — reducen demostrablemente las intrusiones, bajan el cortisol y mejoran la función inmune.',

  'psy.prokr.beziehungen.label': 'Relaciones',
  'psy.prokr.beziehungen.q': '¿Vale la pena mantener relaciones durante períodos de estudio intenso?',
  'psy.prokr.beziehungen.a': 'Sin duda. El Estudio Harvard de Desarrollo Adulto (desde 1938, Waldinger & Schulz, 2023) — el estudio longitudinal más largo de la historia — muestra: las relaciones de calidad son el predictor más fuerte de salud, satisfacción vital y función cognitiva en la vejez. El apoyo social amortigua el estrés mediante la reducción de la actividad del eje HHA (Cohen & Wills, 1985). Lo decisivo no es la cantidad sino la calidad: una hora de atención focalizada vale más que horas de presencia sin conexión.',

  'psy.prokr.hobbys.label': 'Hobbies y equilibrio',
  'psy.prokr.hobbys.q': '¿Son los hobbies una pérdida de tiempo cuando se debería estar estudiando?',
  'psy.prokr.hobbys.a': 'Al contrario: los hobbies empleados estratégicamente aumentan el rendimiento de estudio. La actividad física mejora las funciones ejecutivas, la consolidación de memoria y la neurogénesis hipocampal (Hillman et al., 2008). La teoría de recuperación del esfuerzo (Meijman & Mulder, 1998) muestra: la recuperación requiere actividades que utilizan recursos psicológicos diferentes a la actividad principal — el deporte después del estudio mental es óptimo. Pero solo cuando están limitados en tiempo y planificados conscientemente, no como sustituto de procrastinación.',

  'psy.prokr.gaming.label': 'Gaming',
  'psy.prokr.gaming.q': '¿El gaming es realmente perjudicial o es un pasatiempo como cualquier otro?',
  'psy.prokr.gaming.a': 'El gaming activa el sistema dopaminérgico de recompensa con programas de refuerzo de razón variable — el programa más adictivo (Skinner). Se vuelve problemático por dos mecanismos: primero, la adaptación hedónica — el nivel basal natural de dopamina se regula a la baja, haciendo que estudiar parezca menos gratificante (Volkow et al., 2011). Segundo, costos de oportunidad: 3 horas diarias de gaming = 1095 horas/año — el equivalente a 137 días laborales completos. Gaming controlado (máx. 5h/semana) como recompensa planificada utiliza terapéuticamente el principio de Premack.',

  'psy.prokr.passiver_konsum.label': 'Consumo pasivo',
  'psy.prokr.passiver_konsum.q': '¿Por qué el streaming se siente tan satisfactorio aunque se sabe que es improductivo?',
  'psy.prokr.passiver_konsum.a': 'El consumo pasivo de medios proporciona recompensa de bajo umbral sin esfuerzo — lo que parece ideal para el cerebro procrastinador (Tice et al., 2001: reparación del ánimo como motivo). La transportación narrativa (Green & Brock, 2000) crea inmersión en mundos ficticios que reduce el estrés a corto plazo pero agrava el problema a largo plazo. Uso controlado como recompensa (máx. 3h/semana) con final predeterminado y temporizador es la recomendación basada en evidencia.',

  'psy.prokr.ernaehrung_zucker.label': 'Azúcar y energía',
  'psy.prokr.ernaehrung_zucker.q': '¿Puede el azúcar realmente deteriorar el rendimiento cognitivo?',
  'psy.prokr.ernaehrung_zucker.a': 'Sí, a través del ciclo glucémico: alimentos de alto índice glucémico causan pico rápido de glucosa → liberación de insulina → hipoglucemia reactiva → caída de energía, pérdida de concentración y antojos (Ludwig, 2002). A largo plazo, el consumo crónicamente alto de azúcar eleva marcadores inflamatorios (CRP, IL-6) que promueven neuroinflamación y deterioro cognitivo (Beilharz et al., 2015). La alimentación de bajo índice glucémico (avena, frutos secos, legumbres) estabiliza la glucemia y el rendimiento cognitivo durante todo el día.',

  'psy.prokr.koerperpflege.label': 'Cuidado personal',
  'psy.prokr.koerperpflege.q': '¿El cuidado personal tiene realmente efectos sobre el rendimiento psicológico?',
  'psy.prokr.koerperpflege.a': 'Sí — mediante el mecanismo de enclothed cognition (Adam & Galinsky, 2012): la vestimenta y la apariencia influyen no solo en la percepción externa, sino en el propio rendimiento cognitivo. Participantes que vestían una bata de médico mostraron rendimiento de atención significativamente mejor. El cuidado personal funciona como señal de autoeficacia: el dominio rutinario del autocuidado diario fortalece la sensación de control y reduce la indefensión — un factor central en la procrastinación depresiva.',

  'psy.prokr.koerperhaltung.label': 'Postura',
  'psy.prokr.koerperhaltung.q': '¿Puede la postura al trabajar realmente influir en el pensamiento y el ánimo?',
  'psy.prokr.koerperhaltung.a': 'La cognición encarnada (embodied cognition) confirma: la postura influye en emoción y cognición bidireccionalmente. Nair et al. (2015) confirmaron: sentarse erguido mejora significativamente el ánimo, la autoestima y la resiliencia al estrés comparado con una postura encorvada. La ergonomía en el puesto de trabajo reduce las molestias musculoesqueléticas que deterioran crónicamente la concentración y la resistencia.',

  'psy.prokr.rhetorik.label': 'Comunicación',
  'psy.prokr.rhetorik.q': '¿Por qué la capacidad comunicativa se valora a menudo más que los conocimientos técnicos?',
  'psy.prokr.rhetorik.a': 'La investigación de thin-slicing de Ambady y Rosenthal (1993) mostró: las personas forman juicios sobre competencia, simpatía y confiabilidad en fracciones de segundo — basándose en el comportamiento no verbal, no en el contenido. En contextos profesionales, la competencia comunicativa correlaciona más fuertemente con el éxito profesional que la expertise (Harvard Business Review, 2012). La práctica deliberada (Ericsson, 1993) — práctica dirigida con retroalimentación — es el único camino empíricamente probado hacia una retórica excelente.',

  'psy.prokr.raumordnung.label': 'Orden y entorno',
  'psy.prokr.raumordnung.q': '¿Ordenar es realmente relevante para la productividad o es solo bienestar estético?',
  'psy.prokr.raumordnung.a': 'Más que estética: el desorden visual compite por recursos atencionales (McMains & Kastner, 2011, Princeton Neuroscience Institute). El cerebro procesa estímulos visuales irrelevantes de forma inconsciente — ocupando capacidad cognitiva y aumentando la tasa de errores. Saxbe y Repetti (2010) encontraron: personas que describían su hogar como «desordenado» mostraban curvas diurnas de cortisol más planas — un biomarcador de estrés crónico. Las rutinas diarias de orden de 5 minutos utilizan el habit stacking (Clear, 2018) y reducen acumulativamente la carga cognitiva.',

  'psy.prokr.gewohnheiten.label': 'Hábitos',
  'psy.prokr.gewohnheiten.q': '¿Por qué es tan difícil romper malos hábitos incluso cuando realmente se quiere?',
  'psy.prokr.gewohnheiten.a': 'Los hábitos son controlados por los ganglios basales — una región cerebral filogenéticamente antigua que almacena secuencias de acción automatizadas (Graybiel, 2008). El bucle del hábito (Duhigg, 2012): señal → rutina → recompensa. La fuerza de voluntad sola fracasa porque consume recursos prefrontales limitados (ego depletion, Baumeister et al., 1998). Estrategias efectivas: eliminar señales (control de estímulos), sustituir la rutina por una alternativa compatible, rediseñar el entorno (choice architecture) y trabajo de identidad: «Soy alguien que...» en lugar de «Estoy intentando...» (Clear, 2018: hábitos basados en identidad).',

  'psy.prokr.ernaehrung.label': 'Nutrición',
  'psy.prokr.ernaehrung.q': '¿Cuánto influye realmente la nutrición en el rendimiento cognitivo?',
  'psy.prokr.ernaehrung.a': 'El cerebro consume ~20% del metabolismo basal con solo el 2% del peso corporal (Raichle & Gusnard, 2002). El estudio PREDIMED (2013, n=7447) mostró: la dieta mediterránea reduce significativamente el deterioro cognitivo, el riesgo cardiovascular y la depresión. Los ácidos grasos omega-3 (DHA) son componentes estructurales de las membranas neuronales. El desayuno con bajo índice glucémico mejora la memoria de trabajo y la atención (Ingwersen et al., 2007). La deshidratación de solo el 2% del peso corporal deteriora la atención y la memoria a corto plazo (Ganio et al., 2011).',

  'psy.prokr.schlaf.label': 'Sueño',
  'psy.prokr.schlaf.q': '¿No se puede realmente arreglárselas con menos sueño si se usa el tiempo para estudiar?',
  'psy.prokr.schlaf.a': 'No — es una de las ilusiones de autoevaluación mejor documentadas. Van Dongen et al. (2003) mostraron: las personas que crónicamente duermen 6 horas subestiman dramáticamente su deterioro cognitivo — tras 14 días, su rendimiento equivale al de alguien tras 48h de privación total de sueño, mientras se sienten «normales». El sueño no es tiempo perdido sino consolidación activa: el hipocampo reproduce contenidos de aprendizaje durante el sueño profundo 20 veces más rápido que en vigilia (Euston et al., 2007). 6h de estudio + 8h de sueño > 8h de estudio + 6h de sueño — la consolidación marca la diferencia.',

  'psy.prokr.smartphone.label': 'Smartphone',
  'psy.prokr.smartphone.q': '¿Es el uso del smartphone realmente tan problemático, o es una exageración?',
  'psy.prokr.smartphone.a': 'La evidencia es clara: Ward et al. (2017, «Brain Drain») mostraron que la mera presencia de un smartphone — incluso apagado — reduce la capacidad de memoria de trabajo y la inteligencia fluida. El mecanismo: la supresión del impulso de alcanzar el teléfono consume recursos cognitivos (teoría de procesos irónicos, Wegner, 1994). Cada notificación genera un cambio de atención; Mark et al. (2008) mostraron: tras una interrupción se necesitan en promedio 23 minutos y 15 segundos para volver a la profundidad de concentración original.',

  'psy.prokr.finanzen.label': 'Finanzas',
  'psy.prokr.finanzen.q': '¿Por qué el estrés financiero causa un deterioro cognitivo desproporcionado?',
  'psy.prokr.finanzen.a': 'Mani et al. (2013, Science) mostraron: las preocupaciones financieras consumen ancho de banda cognitivo necesario para otras tareas — el efecto sobre el CI equivale al de una noche sin dormir o al alcoholismo crónico. Mullainathan y Shafir (2013) acuñaron el término «mentalidad de escasez» (scarcity mindset): la escasez tunneliza la atención hacia el problema inmediato y reduce la capacidad para la planificación a largo plazo. El ahorro automatizado, estructuras presupuestarias claras y la regla de 48 horas para compras impulsivas reducen la carga cognitiva y mejoran la calidad de las decisiones en todos los ámbitos de la vida.',

  'psy.prokr.summary.title': 'El mensaje central basado en evidencia',
  'psy.prokr.summary.text':  'La procrastinación no es un defecto de carácter, sino un déficit de regulación emocional. La investigación muestra consistentemente: no la fuerza de voluntad, sino el diseño del entorno, los planes de implementación y el trabajo de identidad son las contramedidas más efectivas. Cada decisión que prioriza el alivio a corto plazo sobre el bienestar a largo plazo se compone — como el interés compuesto, solo en contra de los propios objetivos. La buena noticia: la neuroplasticidad significa que nuevos patrones pueden establecerse a cualquier edad. El mejor momento para empezar fue ayer. El segundo mejor es ahora.',
};

export default es;